// Topic-wise notes for Class 10, keyed by chapter slug. n(topic, ...points) makes one topic.
const n = (topic, ...points) => ({ topic, points });

const QUADRATIC = [
  n('Standard form',
    'A quadratic equation in x has the form ax² + bx + c = 0, where a, b and c are real numbers and a ≠ 0.',
    'A root is a value of x that satisfies the equation. A quadratic equation has at most two roots.'),
  n('Solving by factorisation',
    'Split the middle term so that the two parts have product ac and sum b, factorise, and put each factor equal to zero.',
    'Example: x² − 5x + 6 = 0 gives (x − 2)(x − 3) = 0, so x = 2 or x = 3.'),
  n('Quadratic formula',
    'x = [−b ± √(b² − 4ac)] / 2a.',
    'Write the equation in standard form first, then read off a, b and c with their signs.'),
  n('Nature of roots',
    'The discriminant is D = b² − 4ac.',
    'D > 0: two distinct real roots. D = 0: two equal real roots, each −b/2a. D < 0: no real roots.'),
  n('Sum and product of roots',
    'Sum of the roots = −b/a and product of the roots = c/a.',
    'An equation with roots p and q is x² − (p + q)x + pq = 0.'),
];

const HEIGHTS = [
  n('Terms',
    'The line of sight is the line from the observer’s eye to the object.',
    'Angle of elevation: the angle between the horizontal and the line of sight when the object is above eye level.',
    'Angle of depression: the angle between the horizontal and the line of sight when the object is below eye level.',
    'The angle of depression of B from A equals the angle of elevation of A from B (alternate angles).'),
  n('Method',
    'Draw a clear figure with the right angle, the given angles and the known lengths marked.',
    'Use tan when the height and the horizontal distance are involved; use sin or cos when the slant length (ladder, string, wire) is involved.',
    'With two triangles, take the common side as x, write an equation from each triangle and solve.'),
  n('Values to remember',
    'tan 30° = 1/√3, tan 45° = 1, tan 60° = √3.',
    'Take √3 = 1.732 unless the question says otherwise.',
    'Example: a tower 30 m high seen from a point 30√3 m away has tan θ = 1/√3, so the angle of elevation is 30°.'),
];

const PROBABILITY = [
  n('Definition',
    'P(E) = number of outcomes favourable to E / total number of equally likely outcomes.',
    '0 ≤ P(E) ≤ 1. A sure event has probability 1 and an impossible event has probability 0.',
    'P(not E) = 1 − P(E). The sum of the probabilities of all the elementary events is 1.'),
  n('Sample spaces',
    'One coin: H, T. Two coins: HH, HT, TH, TT. Three coins: 8 outcomes.',
    'One die: 1 to 6. Two dice: 36 outcomes, written as ordered pairs.',
    'Cards: 52 in all, 13 in each of 4 suits (hearts and diamonds red, spades and clubs black). Face cards are the jack, queen and king: 12 in all.'),
  n('Common mistakes',
    'Count (2, 5) and (5, 2) as different outcomes for two dice.',
    '“At least one” is easiest as 1 − P(none).',
    'A probability can never be negative or greater than 1; if it is, recount the outcomes.'),
];

const AP = [
  n('Definition',
    'An arithmetic progression is a list of numbers in which each term is obtained by adding a fixed number d to the previous term.',
    'd is the common difference: d = a₂ − a₁ = a₃ − a₂. It can be positive, negative or zero.',
    'General form: a, a + d, a + 2d, ...'),
  n('nth term',
    'a_n = a + (n − 1)d.',
    'The nth term from the end of an AP with last term l is l − (n − 1)d.',
    'a, b, c are in AP when 2b = a + c.'),
  n('Sum of n terms',
    'S_n = (n/2)[2a + (n − 1)d].',
    'S_n = (n/2)(a + l), where l is the last term.',
    'a_n = S_n − S_(n−1).',
    'Sum of the first n natural numbers = n(n + 1)/2.'),
  n('Problem tips',
    'Three numbers in AP: take them as a − d, a, a + d. Four numbers: a − 3d, a − d, a + d, a + 3d.',
    'In word problems, identify a, d and what is asked: a term (a_n) or a total (S_n).'),
];

const SOLIDS = n('Formulas',
  'Cylinder: curved surface area = 2πrh, total surface area = 2πr(r + h), volume = πr²h.',
  'Cone: slant height l = √(r² + h²), curved surface area = πrl, total surface area = πr(l + r), volume = ⅓πr²h.',
  'Sphere: surface area = 4πr², volume = (4/3)πr³.',
  'Hemisphere: curved surface area = 2πr², total surface area = 3πr², volume = (2/3)πr³.');

export default {
  // ---------- CBSE: NCERT Mathematics ----------
  'real-numbers': {
    summary: 'The Fundamental Theorem of Arithmetic, HCF and LCM by prime factorisation, and proofs of irrationality.',
    notes: [
      n('Fundamental Theorem of Arithmetic',
        'Every composite number can be written as a product of primes, and this factorisation is unique apart from the order of the factors.',
        'Example: 140 = 2² × 5 × 7.'),
      n('HCF and LCM',
        'HCF = product of the smallest power of each common prime factor.',
        'LCM = product of the greatest power of each prime factor involved.',
        'For two positive integers a and b: HCF(a, b) × LCM(a, b) = a × b. This does not hold for three numbers in general.',
        'Example: 6 = 2 × 3 and 20 = 2² × 5, so HCF = 2 and LCM = 60.'),
      n('Irrational numbers',
        'If a prime p divides a², then p divides a.',
        'To prove √2 irrational: assume √2 = a/b in lowest terms, show that 2 divides both a and b, which contradicts the assumption.',
        'The sum or difference of a rational and an irrational number is irrational. The product of a non-zero rational and an irrational number is irrational.'),
      n('Typical questions',
        'Can 6^n end with the digit 0? No, because its prime factorisation has no 5.',
        'For “largest number that divides” use HCF; for “smallest number divisible by” or “meet again” use LCM.'),
    ] },
  'polynomials': {
    summary: 'Zeroes of a polynomial, what they mean on a graph, and the relation between zeroes and coefficients.',
    notes: [
      n('Zeroes and graphs',
        'A zero of p(x) is a value k with p(k) = 0.',
        'The zeroes are the x-coordinates of the points where the graph of y = p(x) meets the x-axis.',
        'A linear polynomial has 1 zero, a quadratic has at most 2 and a cubic has at most 3.',
        'The graph of a quadratic polynomial is a parabola: it opens upwards if a > 0 and downwards if a < 0.'),
      n('Quadratic polynomial',
        'For ax² + bx + c with zeroes α and β: α + β = −b/a and αβ = c/a.',
        'A quadratic polynomial with zeroes α and β is k[x² − (α + β)x + αβ], for any non-zero k.',
        'Example: x² − 5x + 6 has zeroes 2 and 3: sum 5 = −(−5)/1 and product 6 = 6/1.'),
      n('Cubic polynomial',
        'For ax³ + bx² + cx + d with zeroes α, β and γ: α + β + γ = −b/a, αβ + βγ + γα = c/a and αβγ = −d/a.'),
      n('Useful results',
        'α² + β² = (α + β)² − 2αβ.',
        '1/α + 1/β = (α + β)/αβ.'),
    ] },
  'pair-of-linear-equations': {
    summary: 'Solving a pair of linear equations graphically and algebraically, and the conditions for consistency.',
    notes: [
      n('Graphical meaning',
        'Each equation a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0 is a straight line.',
        'Intersecting lines: one solution. Parallel lines: no solution. Coincident lines: infinitely many solutions.'),
      n('Conditions',
        'a₁/a₂ ≠ b₁/b₂: unique solution (consistent).',
        'a₁/a₂ = b₁/b₂ ≠ c₁/c₂: no solution (inconsistent).',
        'a₁/a₂ = b₁/b₂ = c₁/c₂: infinitely many solutions (dependent and consistent).'),
      n('Substitution method',
        'Express one variable in terms of the other from one equation, substitute in the other and solve.'),
      n('Elimination method',
        'Make the coefficients of one variable equal by multiplying the equations by suitable numbers, then add or subtract to remove that variable.'),
      n('Word problems',
        'Choose the two unknowns as x and y, form two equations and solve.',
        'Two-digit number: 10x + y. Speed with and against a current: x + y and x − y.',
        'Check the answer against the words of the problem.'),
    ] },
  'quadratic-equations': { notes: QUADRATIC },
  'arithmetic-progression': {
    summary: 'Arithmetic progressions: the common difference, the nth term and the sum of the first n terms.',
    notes: AP },
  'triangles': {
    summary: 'Similar triangles: the basic proportionality theorem and the criteria for similarity.',
    notes: [
      n('Similar figures',
        'Two figures are similar when they have the same shape, not necessarily the same size.',
        'Two triangles are similar when their corresponding angles are equal and their corresponding sides are in the same ratio.',
        'All congruent figures are similar, but similar figures need not be congruent.'),
      n('Basic Proportionality Theorem (Thales)',
        'A line drawn parallel to one side of a triangle, cutting the other two sides at distinct points, divides those sides in the same ratio.',
        'If DE ∥ BC in △ABC, with D on AB and E on AC, then AD/DB = AE/EC.',
        'Converse: a line that divides two sides of a triangle in the same ratio is parallel to the third side.'),
      n('Criteria for similarity',
        'AA (or AAA): two angles of one triangle equal two angles of the other.',
        'SSS: the three pairs of corresponding sides are in the same ratio.',
        'SAS: one angle is equal and the sides including it are in the same ratio.'),
      n('Writing a proof',
        'Name the triangles with the vertices in matching order: △ABC ~ △PQR means AB/PQ = BC/QR = CA/RP.',
        'State the criterion used, then write the ratio of the sides you need.'),
    ] },
  'coordinate-geometry': {
    summary: 'The distance formula and the section formula.',
    notes: [
      n('Distance formula',
        'Distance between P(x₁, y₁) and Q(x₂, y₂) = √[(x₂ − x₁)² + (y₂ − y₁)²].',
        'Distance of (x, y) from the origin = √(x² + y²).',
        'Three points are collinear if the sum of two of the distances between them equals the third.'),
      n('Section formula',
        'The point dividing the join of (x₁, y₁) and (x₂, y₂) internally in the ratio m₁ : m₂ is ((m₁x₂ + m₂x₁)/(m₁ + m₂), (m₁y₂ + m₂y₁)/(m₁ + m₂)).',
        'Midpoint: ((x₁ + x₂)/2, (y₁ + y₂)/2).',
        'To find the ratio in which a point divides a segment, take the ratio as k : 1.'),
      n('Identifying figures',
        'Parallelogram: the diagonals have the same midpoint.',
        'Rhombus: four equal sides. Rectangle: opposite sides equal and diagonals equal. Square: four equal sides and equal diagonals.',
        'A point on the x-axis is (x, 0); a point on the y-axis is (0, y).'),
    ] },
  'trigonometry': {
    summary: 'Trigonometric ratios of an acute angle, their values for standard angles and the three basic identities.',
    notes: [
      n('Ratios',
        'In a right-angled triangle, for an acute angle A: sin A = opposite side / hypotenuse, cos A = adjacent side / hypotenuse, tan A = opposite side / adjacent side.',
        'cosec A = 1/sin A, sec A = 1/cos A, cot A = 1/tan A.',
        'tan A = sin A / cos A and cot A = cos A / sin A.',
        'sin A and cos A are never greater than 1; sec A and cosec A are never less than 1.'),
      n('Standard angles',
        'sin: 0° → 0, 30° → ½, 45° → 1/√2, 60° → √3/2, 90° → 1.',
        'cos: 0° → 1, 30° → √3/2, 45° → 1/√2, 60° → ½, 90° → 0.',
        'tan: 0° → 0, 30° → 1/√3, 45° → 1, 60° → √3, 90° → not defined.'),
      n('Identities',
        'sin²A + cos²A = 1.',
        '1 + tan²A = sec²A.',
        '1 + cot²A = cosec²A.'),
      n('Tips',
        'Given one ratio, draw the triangle, find the third side by Pythagoras theorem and read off the others.',
        'To prove an identity, start with the more complicated side and convert everything to sin and cos if nothing else works.',
        'sin²A means (sin A)². sin(A + B) is not sin A + sin B.'),
    ] },
  'applications-of-trigonometry': {
    summary: 'Heights and distances: using angles of elevation and depression to find lengths.',
    notes: HEIGHTS },
  'circles': {
    summary: 'Tangents to a circle and the two tangent theorems.',
    notes: [
      n('Tangent and secant',
        'A tangent touches the circle at exactly one point, the point of contact. A secant cuts it at two points.',
        'From a point inside a circle no tangent can be drawn; from a point on the circle, exactly one; from a point outside, exactly two.'),
      n('Theorem 1',
        'The tangent at any point of a circle is perpendicular to the radius through the point of contact.'),
      n('Theorem 2',
        'The lengths of the two tangents drawn from an external point to a circle are equal.',
        'The line joining the external point to the centre bisects the angle between the tangents.'),
      n('Useful results',
        'Length of the tangent from a point at distance d from the centre = √(d² − r²).',
        'If PA and PB are tangents from P to a circle with centre O, then ∠APB + ∠AOB = 180°.',
        'For a quadrilateral ABCD circumscribing a circle, AB + CD = AD + BC.'),
    ] },
  'areas-related-to-circles': {
    summary: 'Areas and perimeters of sectors and segments of a circle.',
    notes: [
      n('Sector',
        'A sector is the region between two radii and the arc between them.',
        'For angle θ in degrees: arc length = (θ/360) × 2πr and area of sector = (θ/360) × πr².',
        'Perimeter of a sector = arc length + 2r.',
        'Area of the major sector = πr² − area of the minor sector.'),
      n('Segment',
        'A segment is the region between a chord and its arc.',
        'Area of the minor segment = area of the sector − area of the triangle formed by the two radii and the chord.',
        'Area of the major segment = πr² − area of the minor segment.'),
      n('Triangle inside the sector',
        'For θ = 90°, the triangle has area ½r². For θ = 60°, it is equilateral with area (√3/4)r².',
        'For θ = 120°, the triangle has area (√3/4)r².'),
      n('Clock problems',
        'The minute hand turns 6° per minute. The hour hand turns 30° per hour, that is ½° per minute.'),
    ] },
  'surface-areas-and-volumes': {
    summary: 'Surface area and volume of solids made by joining cylinders, cones, spheres, hemispheres and cuboids.',
    notes: [
      SOLIDS,
      n('Surface area of a combination',
        'Add only the surfaces that can be seen. The faces where the solids are joined are not included.',
        'Example: a cone on a hemisphere of the same radius has surface area πrl + 2πr².'),
      n('Volume of a combination',
        'Add the volumes of the parts; for a hollowed-out solid, subtract the part removed.',
        'Example: a cylinder with a hemisphere at each end has volume πr²h + (4/3)πr³, where h is the height of the cylindrical part.'),
      n('Tips',
        'Work out the height of each part from the total height.',
        'Keep the units the same. 1 litre = 1000 cm³ and 1 m³ = 1000 litres.'),
    ] },
  'statistics': {
    summary: 'Mean, median and mode of grouped data.',
    notes: [
      n('Mean',
        'Class mark x = (lower limit + upper limit)/2.',
        'Direct method: mean = Σfx / Σf.',
        'Assumed mean method: mean = a + Σfd / Σf, where d = x − a.',
        'Step-deviation method: mean = a + (Σfu / Σf) × h, where u = (x − a)/h and h is the class size.'),
      n('Mode',
        'The modal class is the class with the highest frequency.',
        'Mode = l + [(f₁ − f₀) / (2f₁ − f₀ − f₂)] × h, where l is the lower limit of the modal class, f₁ its frequency, f₀ and f₂ the frequencies of the classes before and after it, and h the class size.'),
      n('Median',
        'Write the cumulative frequencies. The median class is the class whose cumulative frequency is just greater than n/2, where n = Σf.',
        'Median = l + [(n/2 − cf) / f] × h, where l is the lower limit of the median class, cf the cumulative frequency of the class before it, f its frequency and h the class size.'),
      n('Points to remember',
        'The classes must be continuous before using the median or mode formula.',
        'Empirical relation: 3 median = mode + 2 mean.'),
    ] },
  'probability': {
    summary: 'Theoretical probability of an event, with coins, dice and cards.',
    notes: PROBABILITY },

  // ---------- ICSE: Selina Concise Mathematics ----------
  'icse-gst': {
    summary: 'Goods and Services Tax: CGST, SGST and IGST, and input tax credit.',
    notes: [
      n('Basics',
        'GST is a tax on the supply of goods and services, charged as a percentage of the taxable value.',
        'The rate depends on the item and is given in the question.',
        'If a discount is given, GST is charged on the price after the discount.'),
      n('Sale within a state',
        'The GST is split equally into CGST (to the central government) and SGST (to the state government).',
        'Example: at 18% GST on ₹5,000, CGST = 9% = ₹450 and SGST = 9% = ₹450. The bill is ₹5,900.'),
      n('Sale between states',
        'A single tax, IGST, is charged at the full rate and goes to the central government.'),
      n('Input tax credit',
        'A dealer pays GST on purchases (input GST) and collects GST on sales (output GST).',
        'GST payable to the government = output GST − input GST.',
        'So each dealer in the chain pays tax only on the value added.'),
    ] },
  'icse-banking-recurring-deposit-accounts': {
    summary: 'Interest and maturity value of a recurring deposit account.',
    notes: [
      n('Recurring deposit',
        'A fixed sum P is deposited every month for n months. Interest is paid at r% per annum.'),
      n('Formulas',
        'Interest I = P × n(n + 1)/(2 × 12) × r/100.',
        'Maturity value = total deposited + interest = P × n + I.'),
      n('Types of question',
        'Find the maturity value: calculate I, then add P × n.',
        'Find the monthly deposit or the rate: put the given maturity value in the formula and solve.',
        'Find the time: this gives a quadratic equation in n; take the positive root.'),
      n('Example',
        '₹500 per month for 12 months at 8%: I = 500 × (12 × 13)/24 × 8/100 = ₹260. Maturity value = 6,000 + 260 = ₹6,260.'),
    ] },
  'icse-shares-and-dividend': {
    summary: 'Nominal value and market value of shares, dividend and return on investment.',
    notes: [
      n('Terms',
        'Nominal value (NV, face value) is the value printed on the share. Market value (MV) is the price at which it is bought or sold.',
        'At par: MV = NV. At a premium: MV > NV. At a discount: MV < NV.',
        'Dividend is the share of profit paid to shareholders, always calculated on the nominal value.'),
      n('Formulas',
        'Number of shares = sum invested / MV of one share.',
        'Annual dividend = number of shares × rate of dividend × NV / 100.',
        'Return % = (dividend on one share / MV of one share) × 100.',
        'Rate of dividend × NV = return % × MV.'),
      n('Example',
        '₹100 shares at ₹125 paying 10%: an investment of ₹5,000 buys 40 shares, the dividend is 40 × 10 = ₹400 and the return is 400/5000 × 100 = 8%.'),
    ] },
  'icse-linear-inequations': {
    summary: 'Solving linear inequations in one variable and representing the solution on a number line.',
    notes: [
      n('Rules',
        'Adding or subtracting the same number on both sides keeps the inequality sign.',
        'Multiplying or dividing by a positive number keeps the sign.',
        'Multiplying or dividing by a negative number reverses the sign.',
        'If the sides are interchanged, the sign is reversed: a < b means b > a.'),
      n('Solution set',
        'The replacement set (N, W, Z or R) decides which values are allowed.',
        'For N, W or Z list the elements: {x : −2 ≤ x < 3, x ∈ Z} = {−2, −1, 0, 1, 2}.',
        'For R the solution is a continuous part of the number line.'),
      n('Combining inequations',
        'For a double inequation such as −3 < 2x − 1 ≤ 5, solve the two parts separately and take the values common to both: −1 < x ≤ 3.',
        '“And” means intersection of the solution sets; “or” means union.'),
      n('Number line',
        'Use a filled circle for an end value that is included (≤ or ≥) and a hollow circle for one that is not (< or >).'),
    ] },
  'icse-quadratic-equations': { notes: [
    ...QUADRATIC.slice(0, 4),
    n('Answers to a given accuracy',
      'When the roots are not rational, use the formula and round off as asked.',
      'Correct to two decimal places: work to three places, then round. For significant figures, count from the first non-zero digit.'),
  ] },
  'icse-solving-problems-based-on-quadratic-equations': {
    summary: 'Forming quadratic equations from word problems and choosing the root that fits.',
    notes: [
      n('Steps',
        'Read the problem and let the unknown be x.',
        'Write the other quantities in terms of x and form the equation from the given condition.',
        'Solve, then reject any root that does not fit: a length, an age or a number of people cannot be negative.'),
      n('Numbers and ages',
        'Consecutive numbers: x and x + 1. Consecutive even or odd numbers: x and x + 2.',
        'A number and its reciprocal: x and 1/x.',
        'Ages n years ago and n years from now: x − n and x + n.'),
      n('Geometry',
        'Rectangle: area = length × breadth and perimeter = 2(length + breadth).',
        'Right-angled triangle: use Pythagoras theorem.'),
      n('Time, distance and work',
        'Time = distance / speed. If the speed changes, write the two times and use the given difference.',
        'With a stream: downstream speed = x + y and upstream speed = x − y.',
        'Cost per article = total cost / number of articles.'),
    ] },
  'icse-ratio-and-proportion': {
    summary: 'Ratios, proportion, continued proportion and the properties of proportion.',
    notes: [
      n('Ratios',
        'Duplicate ratio of a : b is a² : b². Triplicate ratio is a³ : b³.',
        'Sub-duplicate ratio is √a : √b. Sub-triplicate ratio is ∛a : ∛b.',
        'Reciprocal ratio of a : b is b : a. The compound ratio of a : b and c : d is ac : bd.'),
      n('Proportion',
        'a, b, c, d are in proportion when a : b = c : d, that is ad = bc. d is the fourth proportional.',
        'a, b, c are in continued proportion when a : b = b : c, that is b² = ac.',
        'b is the mean proportional between a and c: b = √(ac). c is the third proportional to a and b.'),
      n('Properties of proportion',
        'If a/b = c/d, then b/a = d/c (invertendo) and a/c = b/d (alternendo).',
        '(a + b)/b = (c + d)/d (componendo) and (a − b)/b = (c − d)/d (dividendo).',
        '(a + b)/(a − b) = (c + d)/(c − d) (componendo and dividendo).'),
      n('Method for proofs',
        'Put a/b = c/d = k, so that a = bk and c = dk, and substitute in both sides.',
        'For continued proportion a/b = b/c = k, use b = ck and a = ck².'),
    ] },
  'icse-remainder-and-factor-theorems': {
    summary: 'Finding remainders without division and using the factor theorem to factorise polynomials.',
    notes: [
      n('Remainder theorem',
        'When f(x) is divided by (x − a), the remainder is f(a).',
        'Divided by (x + a), the remainder is f(−a). Divided by (ax + b), it is f(−b/a).'),
      n('Factor theorem',
        '(x − a) is a factor of f(x) if and only if f(a) = 0.'),
      n('Factorising a cubic',
        'Try x = 1, −1, 2, −2, ... (factors of the constant term) until f(a) = 0, which gives the factor (x − a).',
        'Divide f(x) by (x − a) to get a quadratic, then factorise the quadratic.',
        'Example: f(x) = x³ − 6x² + 11x − 6. f(1) = 0, so (x − 1) is a factor; f(x) = (x − 1)(x² − 5x + 6) = (x − 1)(x − 2)(x − 3).'),
      n('Finding unknown constants',
        'If (x − a) is a factor, put f(a) = 0. If a remainder is given, put f(a) equal to that remainder.',
        'Two conditions give two equations for two unknowns.'),
    ] },
  'icse-matrices': {
    summary: 'Matrices: order, types, addition, multiplication by a number and matrix multiplication.',
    notes: [
      n('Order and types',
        'A matrix with m rows and n columns has order m × n.',
        'Row matrix: one row. Column matrix: one column. Square matrix: rows = columns.',
        'Zero matrix: every element is 0. Identity matrix I: a square matrix with 1 on the leading diagonal and 0 elsewhere.',
        'Two matrices are equal when they have the same order and equal corresponding elements.'),
      n('Addition and scalar multiplication',
        'Matrices can be added or subtracted only when they have the same order; add or subtract the corresponding elements.',
        'To multiply a matrix by a number, multiply every element by it.',
        'The transpose is obtained by interchanging rows and columns.'),
      n('Multiplication',
        'AB is defined only when the number of columns of A equals the number of rows of B. If A is m × n and B is n × p, AB is m × p.',
        'Each element of AB is the sum of the products of a row of A with a column of B.',
        'In general AB ≠ BA. AI = IA = A.',
        'AB = 0 does not mean A = 0 or B = 0.'),
      n('Solving matrix equations',
        'First fix the order of the unknown matrix from the orders of the other matrices, write it with unknown elements, multiply out and compare elements.'),
    ] },
  'icse-arithmetic-progression': {
    summary: 'Arithmetic progressions: the common difference, the nth term and the sum of n terms.',
    notes: AP },
  'icse-geometric-progression': {
    summary: 'Geometric progressions: the common ratio, the nth term and the sum of n terms.',
    notes: [
      n('Definition',
        'A geometric progression is a sequence in which each term is obtained by multiplying the previous term by a fixed non-zero number r, the common ratio.',
        'General form: a, ar, ar², ar³, ...'),
      n('nth term',
        'T_n = a × r^(n−1).',
        'a, b, c are in GP when b² = ac.'),
      n('Sum of n terms',
        'S_n = a(r^n − 1)/(r − 1) when r > 1.',
        'S_n = a(1 − r^n)/(1 − r) when r < 1.',
        'When r = 1, S_n = na.'),
      n('Problem tips',
        'Three numbers in GP: take them as a/r, a, ar, so that their product is a³.',
        'Dividing one term by another removes a and leaves a power of r.'),
    ] },
  'icse-reflection': {
    summary: 'Reflection of points in the axes, the origin and lines parallel to the axes.',
    notes: [
      n('Rules',
        'Reflection in the x-axis: (x, y) → (x, −y).',
        'Reflection in the y-axis: (x, y) → (−x, y).',
        'Reflection in the origin: (x, y) → (−x, −y).',
        'Reflection in the line x = a: (x, y) → (2a − x, y). In the line y = b: (x, y) → (x, 2b − y).'),
      n('Invariant points',
        'A point is invariant when its image is the point itself.',
        'Points on the mirror line are invariant: points on the x-axis for reflection in the x-axis, and points on the y-axis for reflection in the y-axis.',
        'Only the origin is invariant under reflection in the origin.'),
      n('Properties',
        'The mirror line is the perpendicular bisector of the segment joining a point and its image.',
        'Reflection keeps lengths and angles the same, so a figure and its image are congruent.',
        'In graph questions, name the figure formed and write the equation of the line of symmetry if asked.'),
    ] },
  'icse-section-and-mid-point-formula': {
    summary: 'The section formula, the mid-point formula and the centroid of a triangle.',
    notes: [
      n('Section formula',
        'The point dividing the join of (x₁, y₁) and (x₂, y₂) in the ratio m₁ : m₂ is ((m₁x₂ + m₂x₁)/(m₁ + m₂), (m₁y₂ + m₂y₁)/(m₁ + m₂)).',
        'To find the ratio, take it as k : 1.',
        'A point on the x-axis has y = 0 and a point on the y-axis has x = 0; use this to find the ratio in which an axis divides a segment.'),
      n('Mid-point formula',
        'Midpoint = ((x₁ + x₂)/2, (y₁ + y₂)/2).',
        'The diagonals of a parallelogram have the same midpoint; use this to find a missing vertex.'),
      n('Centroid',
        'The centroid of a triangle with vertices (x₁, y₁), (x₂, y₂), (x₃, y₃) is ((x₁ + x₂ + x₃)/3, (y₁ + y₂ + y₃)/3).',
        'The centroid divides each median in the ratio 2 : 1 from the vertex.'),
      n('Points of trisection',
        'They divide the segment in the ratios 1 : 2 and 2 : 1.'),
    ] },
  'icse-equation-of-a-line': {
    summary: 'Slope of a line, conditions for parallel and perpendicular lines, and the equation of a line in its different forms.',
    notes: [
      n('Slope',
        'Slope m = tan θ, where θ is the inclination: the angle the line makes with the positive direction of the x-axis.',
        'Slope of the line through (x₁, y₁) and (x₂, y₂) = (y₂ − y₁)/(x₂ − x₁).',
        'A line parallel to the x-axis has slope 0. The slope of a line parallel to the y-axis is not defined.'),
      n('Parallel and perpendicular lines',
        'Parallel lines have equal slopes: m₁ = m₂.',
        'Perpendicular lines have slopes with product −1: m₁ × m₂ = −1.',
        'Three points A, B, C are collinear when slope of AB = slope of BC.'),
      n('Equation of a line',
        'Slope-intercept form: y = mx + c, where c is the y-intercept.',
        'Point-slope form: y − y₁ = m(x − x₁).',
        'Two-point form: find the slope from the two points, then use the point-slope form.',
        'For ax + by + c = 0, slope = −a/b and y-intercept = −c/b.'),
      n('Typical questions',
        'A point lies on a line if its coordinates satisfy the equation of the line.',
        'Intercepts: put y = 0 for the x-intercept and x = 0 for the y-intercept.',
        'Perpendicular bisector of AB: it passes through the midpoint of AB with slope −1/(slope of AB).'),
    ] },
  'icse-similarity': {
    summary: 'Similar triangles, the basic proportionality theorem, areas of similar triangles, and maps and models.',
    notes: [
      n('Conditions for similarity',
        'AA: two angles of one triangle equal two angles of the other.',
        'SAS: one angle equal and the sides including it proportional.',
        'SSS: all three pairs of corresponding sides proportional.',
        'In similar triangles, corresponding sides are proportional, and so are corresponding altitudes and medians.'),
      n('Basic proportionality theorem',
        'A line parallel to one side of a triangle divides the other two sides proportionally.',
        'Conversely, a line dividing two sides of a triangle proportionally is parallel to the third side.'),
      n('Areas',
        'The ratio of the areas of two similar triangles equals the ratio of the squares of their corresponding sides.'),
      n('Maps and models',
        'With scale factor k: length on the model = k × actual length.',
        'Area on the model = k² × actual area.',
        'Volume of the model = k³ × actual volume.'),
    ] },
  'icse-loci': {
    summary: 'Loci: the path of a point moving under given conditions, and the standard constructions for them.',
    notes: [
      n('Meaning',
        'A locus is the set of all points, and only those points, that satisfy a given condition.'),
      n('Standard loci',
        'Points equidistant from two fixed points: the perpendicular bisector of the segment joining them.',
        'Points equidistant from two intersecting lines: the pair of bisectors of the angles between the lines.',
        'Points at a fixed distance from a fixed point: a circle with that point as centre.',
        'Points at a fixed distance from a line: a pair of lines parallel to it, one on each side.',
        'Points equidistant from two parallel lines: the line midway between them and parallel to both.'),
      n('In a triangle',
        'The point equidistant from the three vertices is the circumcentre, where the perpendicular bisectors of the sides meet.',
        'The point equidistant from the three sides is the incentre, where the bisectors of the angles meet.'),
      n('Construction questions',
        'Construct each locus separately; the required point is where the loci intersect.',
        'Show all construction arcs and measure what the question asks for.'),
    ] },
  'icse-circles': {
    summary: 'Angle properties of a circle and cyclic quadrilaterals.',
    notes: [
      n('Angles at the centre and at the circumference',
        'The angle subtended by an arc at the centre is double the angle it subtends at any point on the remaining part of the circle.',
        'Angles in the same segment are equal.',
        'The angle in a semicircle is a right angle.'),
      n('Cyclic quadrilaterals',
        'Opposite angles of a cyclic quadrilateral are supplementary.',
        'The exterior angle of a cyclic quadrilateral equals the interior opposite angle.',
        'If one pair of opposite angles of a quadrilateral is supplementary, the quadrilateral is cyclic.'),
      n('Chords and arcs',
        'Equal chords (or equal arcs) subtend equal angles at the centre and at the circumference.',
        'A cyclic parallelogram is a rectangle. A cyclic trapezium is isosceles.'),
      n('Problem tips',
        'Mark radii: a triangle formed by two radii is isosceles.',
        'Give a reason for every step, naming the property used.'),
    ] },
  'icse-tangents-and-intersecting-chords': {
    summary: 'Tangent properties, intersecting chords, the tangent-secant theorem and the alternate segment theorem.',
    notes: [
      n('Tangents',
        'The tangent at any point of a circle is perpendicular to the radius through the point of contact.',
        'The two tangents drawn from an external point are equal in length, subtend equal angles at the centre and are equally inclined to the line joining the point to the centre.'),
      n('Touching circles',
        'If two circles touch, the point of contact lies on the line joining their centres.',
        'Distance between the centres = sum of the radii when they touch externally, and difference of the radii when they touch internally.'),
      n('Intersecting chords',
        'If two chords AB and CD meet at P, inside or outside the circle, then PA × PB = PC × PD.',
        'Tangent and secant from an external point P: PT² = PA × PB.'),
      n('Alternate segment theorem',
        'The angle between a tangent and a chord through the point of contact equals the angle in the alternate segment.'),
    ] },
  'icse-constructions-circles': {
    summary: 'Constructing tangents to a circle, and the circumscribed and inscribed circles of a triangle and a regular hexagon.',
    notes: [
      n('Tangents from an external point',
        'Join the external point P to the centre O and bisect OP at M.',
        'With centre M and radius MO draw a circle cutting the given circle at A and B. PA and PB are the tangents.',
        'It works because the angle in a semicircle is 90°, so OA is perpendicular to PA.'),
      n('Tangent at a point on the circle',
        'Join the point to the centre and draw the perpendicular to the radius at that point.'),
      n('Circumscribed circle of a triangle',
        'Draw the perpendicular bisectors of any two sides. They meet at the circumcentre O.',
        'With centre O and radius equal to the distance from O to a vertex, draw the circle through all three vertices.'),
      n('Inscribed circle of a triangle',
        'Draw the bisectors of any two angles. They meet at the incentre I.',
        'Draw the perpendicular from I to one side; its length is the radius of the incircle.'),
      n('Regular hexagon',
        'Circumscribed circle: the centre is where the perpendicular bisectors of two sides meet, and the radius equals the side.',
        'Inscribed circle: the same centre, with radius equal to the perpendicular distance from the centre to a side.'),
    ] },
  'icse-cylinder-cone-and-sphere': {
    summary: 'Surface area and volume of cylinders, cones and spheres, their combinations, and melting and recasting.',
    notes: [
      SOLIDS,
      n('Hollow solids',
        'Hollow cylinder with radii R and r: volume of material = π(R² − r²)h, total surface area = 2π(R + r)h + 2π(R² − r²).',
        'Spherical shell: volume of material = (4/3)π(R³ − r³).'),
      n('Combination of solids',
        'Volume: add the volumes of the parts.',
        'Surface area: add only the exposed surfaces.'),
      n('Melting and recasting',
        'The volume stays the same when a solid is melted and recast.',
        'Number of small solids = volume of the large solid / volume of one small solid.',
        'Water displaced by an immersed solid = volume of the solid.'),
    ] },
  'icse-trigonometrical-identities': {
    summary: 'The basic trigonometrical identities, ratios of complementary angles and how to prove identities.',
    notes: [
      n('Identities',
        'sin²A + cos²A = 1.',
        '1 + tan²A = sec²A.',
        '1 + cot²A = cosec²A.',
        'tan A = sin A / cos A, cot A = cos A / sin A, and cosec A, sec A, cot A are the reciprocals of sin A, cos A, tan A.'),
      n('Complementary angles',
        'sin(90° − A) = cos A, cos(90° − A) = sin A.',
        'tan(90° − A) = cot A, cot(90° − A) = tan A.',
        'sec(90° − A) = cosec A, cosec(90° − A) = sec A.'),
      n('Proving identities',
        'Start from the more complicated side and work towards the other.',
        'Change everything to sin and cos when no shorter route is visible.',
        'Take an LCM for sums of fractions; multiply by the conjugate for expressions such as 1 − sin A in a denominator.',
        'Useful forms: sec²A − tan²A = 1 gives (sec A + tan A)(sec A − tan A) = 1.'),
    ] },
  'icse-heights-and-distances': {
    summary: 'Using angles of elevation and depression to find heights and distances.',
    notes: HEIGHTS },
  'icse-graphical-representation-histograms-and-ogives': {
    summary: 'Drawing histograms and ogives, and reading the mode, median and quartiles from them.',
    notes: [
      n('Histogram',
        'Draw rectangles on continuous class intervals with heights equal to the frequencies. There are no gaps between the rectangles.',
        'If the classes are inclusive (10–19, 20–29), make them continuous first (9.5–19.5, 19.5–29.5).',
        'If the first class does not start at zero, show a break (kink) on the x-axis.'),
      n('Mode from a histogram',
        'Join the top-left corner of the tallest rectangle to the top-left corner of the next rectangle, and its top-right corner to the top-right corner of the previous rectangle.',
        'From the point where the two lines cross, draw a perpendicular to the x-axis. The foot of the perpendicular is the mode.'),
      n('Ogive',
        'An ogive is a cumulative frequency curve. Plot cumulative frequency against the upper class limits and join the points with a smooth freehand curve.',
        'Start the curve from the lower limit of the first class, where the cumulative frequency is 0.'),
      n('Reading an ogive',
        'Median: the value on the x-axis for cumulative frequency N/2.',
        'Lower quartile Q₁: the value for N/4. Upper quartile Q₃: the value for 3N/4.',
        'Number above or below a given value: read the cumulative frequency at that value.'),
    ] },
  'icse-measures-of-central-tendency': {
    summary: 'Mean, median, quartiles and mode for raw and grouped data.',
    notes: [
      n('Mean',
        'Raw data: mean = Σx / n.',
        'Direct method: mean = Σfx / Σf.',
        'Short-cut method: mean = A + Σfd / Σf, where d = x − A.',
        'Step-deviation method: mean = A + (Σft / Σf) × i, where t = (x − A)/i and i is the class width.'),
      n('Median of raw data',
        'Arrange the data in order. For n odd, the median is the ((n + 1)/2)th term.',
        'For n even, the median is the mean of the (n/2)th and (n/2 + 1)th terms.'),
      n('Quartiles of raw data',
        'Lower quartile Q₁: the ((n + 1)/4)th term for n odd and the (n/4)th term for n even.',
        'Upper quartile Q₃: the (3(n + 1)/4)th term for n odd and the (3n/4)th term for n even.',
        'Inter-quartile range = Q₃ − Q₁. Semi-inter-quartile range = ½(Q₃ − Q₁).'),
      n('Grouped data',
        'Median and quartiles are read from the ogive at N/2, N/4 and 3N/4.',
        'Mode: the value with the highest frequency; for grouped data it is found from the histogram.'),
    ] },
  'icse-probability': {
    summary: 'Probability of an event, with coins, dice and cards.',
    notes: PROBABILITY },
};
