// Topic-wise notes for Class 9, keyed by chapter slug. n(topic, ...points) makes one topic.
const n = (topic, ...points) => ({ topic, points });

export default {
  // ---------- CBSE: Ganita Manjari ----------
  'orienting-yourself-coordinates': {
    summary: 'The Cartesian plane: axes, coordinates, quadrants and the distance between two points.',
    notes: [
      n('The Cartesian plane',
        'Two perpendicular number lines, the x-axis (horizontal) and the y-axis (vertical), meet at the origin O(0, 0).',
        'A point is written (x, y). x is the abscissa, its distance from the y-axis; y is the ordinate, its distance from the x-axis.',
        'The order matters: (2, 5) and (5, 2) are different points.'),
      n('Quadrants',
        'Quadrant I: (+, +). Quadrant II: (−, +). Quadrant III: (−, −). Quadrant IV: (+, −).',
        'A point on the x-axis has y = 0; a point on the y-axis has x = 0. Points on the axes lie in no quadrant.'),
      n('Distance',
        'For two points on a horizontal line, the distance is the difference of the x-coordinates. On a vertical line it is the difference of the y-coordinates.',
        'Distance between (x₁, y₁) and (x₂, y₂) = √[(x₂ − x₁)² + (y₂ − y₁)²], from the Baudhayana-Pythagoras theorem.',
        'Distance of (x, y) from the origin = √(x² + y²). Example: (3, 4) is 5 units from the origin.'),
      n('Using coordinates',
        'The midpoint of the segment joining (x₁, y₁) and (x₂, y₂) is ((x₁ + x₂)/2, (y₁ + y₂)/2).',
        'To identify a shape from its vertices, compare the lengths of its sides and diagonals.'),
    ] },
  'linear-polynomials': {
    summary: 'Linear patterns and relationships, linear polynomials, their zeroes and their straight-line graphs.',
    notes: [
      n('Linear patterns',
        'A quantity changes linearly when it goes up or down by the same amount at each step.',
        'Example: a taxi fare of ₹50 plus ₹15 per km is 15x + 50 for x km.'),
      n('Linear polynomials',
        'A polynomial in x is a sum of terms of the form ax^n with whole-number powers. Its degree is the highest power.',
        'A linear polynomial has degree 1: p(x) = ax + b with a ≠ 0. a is the coefficient of x and b is the constant term.',
        'The value of p(x) at x = k is found by substituting k. For p(x) = 3x − 6, p(4) = 6.'),
      n('Zero of a polynomial',
        'A zero is a value of x that makes p(x) = 0.',
        'The zero of ax + b is x = −b/a. A linear polynomial has exactly one zero.'),
      n('Graph',
        'The graph of y = ax + b is a straight line.',
        'a is the slope: the change in y when x increases by 1. If a > 0 the line rises (growth); if a < 0 it falls (decay).',
        'b is the y-intercept, where the line cuts the y-axis. The line cuts the x-axis at the zero of the polynomial.'),
    ] },
  'the-world-of-numbers': {
    summary: 'From natural numbers to real numbers: rational and irrational numbers, their decimal forms and the number line.',
    notes: [
      n('Families of numbers',
        'Natural numbers N: 1, 2, 3, ... Whole numbers W: 0, 1, 2, ... Integers Z: ..., −2, −1, 0, 1, 2, ...',
        'Rational numbers Q: numbers of the form p/q with integers p and q, q ≠ 0.',
        'Each family contains the one before it.'),
      n('Decimal expansions',
        'A rational number has a decimal expansion that either terminates (3/8 = 0.375) or repeats (1/3 = 0.333...).',
        'p/q in lowest terms terminates only when q has no prime factor other than 2 and 5.',
        'To convert a repeating decimal to a fraction: let x = 0.777..., then 10x − x = 7, so x = 7/9.'),
      n('Irrational numbers',
        'An irrational number cannot be written as p/q. Its decimal expansion neither terminates nor repeats.',
        'Examples: √2, √3, √5, π.',
        'Rational + irrational is irrational. A non-zero rational × irrational is irrational.'),
      n('Real numbers',
        'Rational and irrational numbers together are the real numbers. Every real number is a point on the number line and every point is a real number.',
        '√2 can be marked on the number line as the diagonal of a unit square.'),
      n('Working with roots',
        '√a × √b = √(ab) and √a / √b = √(a/b) for positive a and b.',
        '(√a + √b)(√a − √b) = a − b.',
        'Rationalising the denominator: 1/(√3 + √2) = (√3 − √2)/(3 − 2) = √3 − √2.'),
    ] },
  'algebraic-identities': {
    summary: 'Algebraic identities seen as areas, and their use in expanding, factorising and simplifying.',
    notes: [
      n('Identities for squares',
        '(a + b)² = a² + 2ab + b²',
        '(a − b)² = a² − 2ab + b²',
        '(a + b)(a − b) = a² − b²',
        '(x + a)(x + b) = x² + (a + b)x + ab',
        'Each one can be pictured as the area of a square or rectangle cut into parts.'),
      n('Three terms and cubes',
        '(a + b + c)² = a² + b² + c² + 2ab + 2bc + 2ca',
        '(a + b)³ = a³ + b³ + 3ab(a + b) and (a − b)³ = a³ − b³ − 3ab(a − b)',
        'a³ + b³ = (a + b)(a² − ab + b²) and a³ − b³ = (a − b)(a² + ab + b²)'),
      n('Factorisation',
        'Take out a common factor first.',
        'Use the identities backwards: 4x² − 9 = (2x + 3)(2x − 3); x² + 6x + 9 = (x + 3)².',
        'Split the middle term: x² + 5x + 6 = x² + 2x + 3x + 6 = (x + 2)(x + 3).'),
      n('Simplifying rational expressions',
        'Factorise the numerator and the denominator, then cancel the common factors. Example: (x² − 9)/(x² + 5x + 6) = (x − 3)(x + 3)/[(x + 2)(x + 3)] = (x − 3)/(x + 2).',
        'Only factors can be cancelled, never terms.'),
    ] },
  'up-and-down-round-and-round': {
    summary: 'Circles: chords, arcs, the angles they subtend and cyclic quadrilaterals.',
    notes: [
      n('Basic terms',
        'A circle is the set of all points in a plane at a fixed distance (the radius) from a fixed point (the centre).',
        'A chord joins two points of the circle. A diameter is a chord through the centre and is the longest chord.',
        'A chord divides the circle into a minor arc and a major arc, and the circular region into two segments.'),
      n('Chords',
        'The perpendicular from the centre to a chord bisects the chord. Conversely, the line joining the centre to the midpoint of a chord is perpendicular to it.',
        'Equal chords are equidistant from the centre and subtend equal angles at the centre. The converses are also true.',
        'Exactly one circle passes through three non-collinear points. Its centre is where the perpendicular bisectors of the joining segments meet.'),
      n('Angles subtended by an arc',
        'The angle subtended by an arc at the centre is double the angle it subtends at any point on the remaining part of the circle.',
        'Angles in the same segment are equal.',
        'The angle in a semicircle is a right angle.'),
      n('Cyclic quadrilaterals',
        'A quadrilateral whose four vertices lie on a circle is cyclic.',
        'Opposite angles of a cyclic quadrilateral add up to 180°. Conversely, if a pair of opposite angles of a quadrilateral adds up to 180°, it is cyclic.',
        'If a segment subtends equal angles at two points on the same side of it, the four points lie on a circle.'),
      n('Problem tips',
        'Join the centre to the ends of a chord to get an isosceles triangle.',
        'For a chord of length 2a at distance d from the centre, r² = a² + d².'),
    ] },
  'perimeter-and-area': {
    summary: 'Perimeter and area of triangles, rectangles and circles, including Heron’s formula, arcs and sectors.',
    notes: [
      n('Triangles',
        'Area = ½ × base × height.',
        'Heron’s formula: area = √[s(s − a)(s − b)(s − c)], where s = (a + b + c)/2 is the semi-perimeter.',
        'Equilateral triangle of side a: area = (√3/4)a² and height = (√3/2)a.'),
      n('Rectangles and other quadrilaterals',
        'Rectangle: perimeter = 2(l + b), area = lb.',
        'Split any quadrilateral into two triangles with a diagonal and add their areas.'),
      n('Circle',
        'Circumference = 2πr. Area = πr².',
        'π is the ratio of the circumference of any circle to its diameter. It is irrational; 22/7 and 3.14 are only approximations.'),
      n('Arcs and sectors',
        'For a sector of angle θ (in degrees): arc length = (θ/360) × 2πr and area = (θ/360) × πr².',
        'Perimeter of a sector = arc length + 2r.',
        'Area of the ring between circles of radii R and r = π(R² − r²).'),
    ] },
  'introduction-to-probability': {
    summary: 'Randomness, sample spaces, and experimental and theoretical probability.',
    notes: [
      n('Random experiments',
        'A random experiment has a result that cannot be predicted with certainty, such as tossing a coin.',
        'The sample space is the set of all possible outcomes. An event is any set of outcomes.'),
      n('The probability scale',
        'Probability runs from 0 (impossible) to 1 (certain). An event as likely to happen as not has probability ½.',
        'It can be written as a fraction, a decimal or a percentage.'),
      n('Experimental probability',
        'P(E) = number of trials in which E happened / total number of trials.',
        'It can change from one set of trials to another, and settles down as the number of trials grows.'),
      n('Theoretical probability',
        'When all outcomes are equally likely, P(E) = number of outcomes favourable to E / total number of outcomes.',
        'P(E) + P(not E) = 1.',
        'Example: for one roll of a die, P(a prime number) = 3/6 = ½.'),
      n('Listing outcomes',
        'Two coins: HH, HT, TH, TT (4 outcomes). Two dice: 36 outcomes.',
        'Use a table or a tree diagram so that no outcome is missed or counted twice.'),
    ] },
  'sequences-and-progressions': {
    summary: 'Sequences given by explicit and recursive rules, and arithmetic and geometric progressions with their sums.',
    notes: [
      n('Sequences',
        'A sequence is an ordered list of numbers; each number is a term.',
        'An explicit rule gives the nth term directly: a_n = 3n + 1 gives 4, 7, 10, ...',
        'A recursive rule gives each term from the earlier ones: a₁ = 4 and a_n = a_(n−1) + 3.'),
      n('Arithmetic progression (AP)',
        'Each term is obtained by adding a fixed number d, the common difference.',
        'nth term: a_n = a + (n − 1)d.',
        'Sum of the first n terms: S_n = (n/2)[2a + (n − 1)d] = (n/2)(first term + last term).',
        '1 + 2 + 3 + ... + n = n(n + 1)/2.'),
      n('Geometric progression (GP)',
        'Each term is obtained by multiplying by a fixed number r, the common ratio.',
        'nth term: a_n = a × r^(n−1).',
        'Sum of the first n terms: S_n = a(r^n − 1)/(r − 1), for r ≠ 1.'),
      n('Telling them apart',
        'A constant difference between consecutive terms means an AP (linear growth). A constant ratio means a GP (exponential growth).',
        'Example: 5, 8, 11, 14 is an AP with d = 3; 5, 10, 20, 40 is a GP with r = 2.'),
    ] },
  'propositions-and-converses': {
    summary: 'Mathematical statements, their converses, counterexamples and what it takes to prove a statement.',
    notes: [
      n('Propositions',
        'A proposition is a statement that is either true or false, but not both.',
        'Many propositions have the form “if X then Y”. X is the hypothesis and Y is the conclusion.'),
      n('Converse',
        'The converse of “if X then Y” is “if Y then X”.',
        'A true statement can have a false converse. “If a number is divisible by 4, it is even” is true; its converse, “if a number is even, it is divisible by 4”, is false.',
        'When a statement and its converse are both true, we say “X if and only if Y”. Example: a triangle is right-angled if and only if its sides satisfy a² + b² = c².'),
      n('Counterexamples',
        'One example where the hypothesis holds but the conclusion fails proves a statement false: 6 is even but not divisible by 4.',
        'Examples that agree with a statement, however many, do not prove it.'),
      n('Proof',
        'A proof shows by logical steps that the conclusion follows from the hypothesis in every case.',
        'Results once proved (theorems) can be used in later proofs. Statements accepted without proof are axioms.'),
    ] },
  'understanding-data': {
    summary: 'Combining data from groups of different sizes: weighted averages, mixtures, percentages and stacked bar charts.',
    notes: [
      n('Weighted average',
        'When groups have different sizes, the combined average is (n₁x₁ + n₂x₂)/(n₁ + n₂), not the simple average of x₁ and x₂.',
        'Example: 30 students average 60 and 20 students average 70. Combined average = (1800 + 1400)/50 = 64.',
        'The combined average always lies between the group averages, closer to that of the larger group.'),
      n('Weighted scores',
        'When items carry different importance, multiply each score by its weight, add, and divide by the total weight.',
        'Example: a test counts 40% and an exam 60%, with scores 80 and 70: 0.4 × 80 + 0.6 × 70 = 74.'),
      n('Mixtures',
        'The concentration of a mixture is the weighted average of the concentrations, with the quantities as weights.',
        'Example: 2 litres of a 10% solution mixed with 3 litres of a 20% solution gives (0.2 + 0.6)/5 = 16%.'),
      n('Percentages and stacked bar charts',
        'A stacked bar chart shows the actual amount of each part and the total.',
        'A 100% stacked bar chart shows only the share of each part, so every bar has the same height.',
        'A share can rise while the actual amount falls, so read both the percentage and the total.'),
    ] },
  'the-world-of-algorithms': {
    summary: 'Algorithms as step-by-step procedures: finding divisors, GCD, LCM and primes, and making procedures efficient.',
    notes: [
      n('What is an algorithm?',
        'An algorithm is a finite list of clear steps that solves a problem for every valid input.',
        'Column addition with carrying is an algorithm: the same steps work for any two numbers.'),
      n('GCD',
        'Subtraction method: replace the larger number by the difference of the two, until both are equal. That value is the GCD. Example: (48, 18) → (30, 18) → (12, 18) → (12, 6) → (6, 6), so the GCD is 6.',
        'Division method: replace the larger number by the remainder on dividing by the smaller, until the remainder is 0. The last divisor is the GCD. 48 = 18 × 2 + 12, 18 = 12 × 1 + 6, 12 = 6 × 2 + 0, so the GCD is 6.',
        'The division method needs far fewer steps.'),
      n('LCM',
        'LCM(a, b) = (a × b) / GCD(a, b). Example: LCM(48, 18) = 864/6 = 144.'),
      n('Divisors and primes',
        'To list the divisors of n, test numbers only up to √n; each divisor d found gives a partner n/d.',
        'n is prime if no number from 2 up to √n divides it.',
        'Prime factorisation: keep dividing by the smallest prime that divides the number.'),
      n('Efficiency',
        'Two algorithms can give the same answer with very different numbers of steps.',
        'A good algorithm is correct, always stops, and uses as few steps as possible.'),
    ] },
  'quadrilaterals': {
    summary: 'Properties of parallelograms, conditions for a quadrilateral to be a parallelogram, and the mid-point theorem.',
    notes: [
      n('Angle sum',
        'The angles of a quadrilateral add up to 360°, because a diagonal divides it into two triangles.'),
      n('Properties of a parallelogram',
        'A diagonal divides a parallelogram into two congruent triangles.',
        'Opposite sides are equal, opposite angles are equal, and the diagonals bisect each other.'),
      n('Conditions for a parallelogram',
        'A quadrilateral is a parallelogram if both pairs of opposite sides are equal.',
        'Or if both pairs of opposite angles are equal.',
        'Or if the diagonals bisect each other.',
        'Or if one pair of opposite sides is both equal and parallel.'),
      n('Special parallelograms',
        'Rectangle: the diagonals are equal. Rhombus: the diagonals are perpendicular. Square: the diagonals are equal and perpendicular.',
        'Conversely, a parallelogram with equal diagonals is a rectangle, and one with perpendicular diagonals is a rhombus.'),
      n('Mid-point theorem',
        'The segment joining the midpoints of two sides of a triangle is parallel to the third side and half of it.',
        'Converse: a line through the midpoint of one side, parallel to another side, bisects the third side.',
        'The midpoints of the sides of any quadrilateral, joined in order, form a parallelogram.'),
    ] },
  'two-variables-one-line': {
    summary: 'Linear equations in two variables, their solutions and their straight-line graphs.',
    notes: [
      n('The equation',
        'A linear equation in two variables has the form ax + by + c = 0, where a and b are not both zero.',
        'A solution is a pair (x, y) that satisfies the equation. There are infinitely many solutions.',
        'To find solutions, choose a value for one variable and solve for the other.'),
      n('Graph',
        'Every solution is a point on a straight line, and every point on the line is a solution.',
        'Two points fix the line; plot a third as a check.',
        'Intercepts: put y = 0 for the x-intercept and x = 0 for the y-intercept.'),
      n('Special lines',
        'x = a is a line parallel to the y-axis; y = b is a line parallel to the x-axis.',
        'y = mx passes through the origin.',
        'In y = mx + c, m is the slope and c is the y-intercept.'),
      n('From words to equations',
        'Example: a notebook costs twice as much as a pen. With x for the pen and y for the notebook, y = 2x, or 2x − y = 0.',
        'Check that the points you use make sense in the situation, for example no negative lengths.'),
    ] },
  'surface-area-and-volume': {
    summary: 'Surface areas and volumes of cuboids, cylinders, cones and spheres.',
    notes: [
      n('Cuboid and cube',
        'Cuboid: total surface area = 2(lb + bh + hl), volume = lbh.',
        'Cube of side a: total surface area = 6a², volume = a³.'),
      n('Cylinder',
        'Curved surface area = 2πrh. Total surface area = 2πr(r + h). Volume = πr²h.'),
      n('Cone',
        'Slant height l = √(r² + h²).',
        'Curved surface area = πrl. Total surface area = πr(l + r).',
        'Volume = ⅓πr²h, one third of the cylinder with the same base and height.'),
      n('Sphere and hemisphere',
        'Sphere: surface area = 4πr², volume = (4/3)πr³.',
        'Hemisphere: curved surface area = 2πr², total surface area = 3πr², volume = (2/3)πr³.'),
      n('Tips',
        'Keep the units the same. 1 m³ = 1000 litres and 1 litre = 1000 cm³.',
        'When a solid is melted and recast, its volume stays the same.'),
    ] },

  // ---------- ICSE: Selina Concise Mathematics ----------
  'icse-rational-and-irrational-numbers': {
    summary: 'Rational and irrational numbers, surds and rationalising the denominator.',
    notes: [
      n('Rational numbers',
        'A rational number has the form p/q with integers p and q, q ≠ 0.',
        'Its decimal form terminates or recurs. It terminates only when q, in lowest terms, has no prime factor other than 2 and 5.',
        'Between any two rational numbers a and b there is another, for example (a + b)/2.'),
      n('Irrational numbers',
        'An irrational number cannot be written as p/q; its decimal form neither terminates nor recurs. Examples: √2, √3, π.',
        'The sum or product of a non-zero rational number and an irrational number is irrational.',
        'Rational and irrational numbers together form the real numbers.'),
      n('Surds',
        'A surd is an irrational root of a rational number, such as √5 or ∛7. √4 is not a surd.',
        '√a × √b = √(ab). Like surds can be added: 3√2 + 5√2 = 8√2.',
        'Simplify by taking out square factors: √72 = √(36 × 2) = 6√2.'),
      n('Rationalisation',
        'Multiply the numerator and denominator by the rationalising factor. For 1/√a it is √a.',
        'For a denominator a + √b use a − √b: 1/(3 + √2) = (3 − √2)/(9 − 2) = (3 − √2)/7.'),
    ] },
  'icse-compound-interest-without-using-formula': {
    summary: 'Finding compound interest year by year, where each year’s amount becomes the next year’s principal.',
    notes: [
      n('Idea',
        'In compound interest, the interest of each period is added to the principal for the next period.',
        'Amount at the end of a year = principal for that year + interest for that year.'),
      n('Working',
        'Interest for a year = principal for that year × rate / 100.',
        'Example: ₹8,000 at 10% for 2 years. Year 1 interest ₹800, amount ₹8,800. Year 2 interest ₹880, amount ₹9,680. CI = ₹1,680.',
        'For half-yearly compounding, halve the rate and treat each half-year as one period.'),
      n('Useful facts',
        'SI and CI are equal for the first year.',
        'The difference between the compound interests of two successive years is the interest on the earlier year’s compound interest.',
        'Rate % = (difference between the CI of two successive years / CI of the earlier year) × 100.'),
    ] },
  'icse-compound-interest-using-formula': {
    summary: 'The compound interest formula and its use for different rates, half-yearly compounding, growth and depreciation.',
    notes: [
      n('Formula',
        'A = P(1 + r/100)^n, where n is the number of years. CI = A − P.',
        'Different rates in successive years: A = P(1 + r₁/100)(1 + r₂/100)...',
        'Compounded half-yearly: A = P(1 + r/200)^(2n).'),
      n('Part of a year',
        'For 2½ years compounded yearly: A = P(1 + r/100)² × (1 + r/200).'),
      n('Growth and depreciation',
        'Growth (population, value): final value = P(1 + r/100)^n.',
        'Depreciation: final value = P(1 − r/100)^n.',
        'To find a value n years ago, divide instead of multiplying.'),
      n('Tips',
        'CI − SI for 2 years = P(r/100)².',
        'Read the question to see whether the amount, the interest or the principal is asked.'),
    ] },
  'icse-expansions': {
    summary: 'Expanding squares and cubes of binomials and trinomials, and the results that follow from them.',
    notes: [
      n('Squares',
        '(a + b)² = a² + 2ab + b² and (a − b)² = a² − 2ab + b².',
        '(a + b)² − (a − b)² = 4ab and (a + b)² + (a − b)² = 2(a² + b²).',
        '(a + b + c)² = a² + b² + c² + 2(ab + bc + ca).'),
      n('Cubes',
        '(a + b)³ = a³ + b³ + 3ab(a + b).',
        '(a − b)³ = a³ − b³ − 3ab(a − b).',
        'a³ + b³ + c³ − 3abc = (a + b + c)(a² + b² + c² − ab − bc − ca). If a + b + c = 0, then a³ + b³ + c³ = 3abc.'),
      n('Results with x and 1/x',
        'x² + 1/x² = (x + 1/x)² − 2 = (x − 1/x)² + 2.',
        'x³ + 1/x³ = (x + 1/x)³ − 3(x + 1/x).',
        'x³ − 1/x³ = (x − 1/x)³ + 3(x − 1/x).'),
    ] },
  'icse-factorisation': {
    summary: 'Factorising by common factors, grouping, splitting the middle term, and the square and cube identities.',
    notes: [
      n('Common factors and grouping',
        'Take out the HCF of all the terms.',
        'Group the terms so that a common bracket appears: ab + bc + ax + cx = b(a + c) + x(a + c) = (a + c)(b + x).'),
      n('Splitting the middle term',
        'For ax² + bx + c, find two numbers with sum b and product ac.',
        'Example: 6x² + 7x − 3 = 6x² + 9x − 2x − 3 = (2x + 3)(3x − 1).'),
      n('Difference of squares',
        'a² − b² = (a + b)(a − b).',
        'Example: x⁴ − 16 = (x² + 4)(x + 2)(x − 2).'),
      n('Sum and difference of cubes',
        'a³ + b³ = (a + b)(a² − ab + b²).',
        'a³ − b³ = (a − b)(a² + ab + b²).'),
    ] },
  'icse-simultaneous-linear-equations': {
    summary: 'Solving a pair of linear equations by substitution, elimination and cross-multiplication, with word problems.',
    notes: [
      n('Substitution',
        'From one equation, write one variable in terms of the other and substitute it in the second equation.'),
      n('Elimination',
        'Multiply the equations by suitable numbers so that the coefficients of one variable become equal, then add or subtract.'),
      n('Cross-multiplication',
        'For a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0: x/(b₁c₂ − b₂c₁) = y/(c₁a₂ − c₂a₁) = 1/(a₁b₂ − a₂b₁).'),
      n('Equations with 1/x and 1/y',
        'Put 1/x = a and 1/y = b to get linear equations in a and b, solve, then find x and y.'),
      n('Word problems',
        'Two-digit number: 10x + y, with x the tens digit and y the units digit.',
        'Fraction: let it be x/y. Ages: let the present ages be x and y.',
        'With a current: downstream speed = x + y and upstream speed = x − y.'),
    ] },
  'icse-indices-exponents': {
    summary: 'Laws of indices, including negative and fractional indices, and solving exponential equations.',
    notes: [
      n('Laws',
        'a^m × a^n = a^(m+n) and a^m ÷ a^n = a^(m−n).',
        '(a^m)^n = a^(mn), (ab)^n = a^n × b^n and (a/b)^n = a^n / b^n.',
        'a⁰ = 1 and a^(−n) = 1/a^n, for a ≠ 0.'),
      n('Fractional indices',
        'a^(1/n) is the nth root of a. a^(m/n) is the nth root of a, raised to the power m.',
        'Example: 8^(2/3) = (∛8)² = 4.'),
      n('Exponential equations',
        'Write both sides as powers of the same base, then equate the indices.',
        'Example: 2^(x+1) = 32 = 2⁵ gives x = 4.'),
    ] },
  'icse-logarithms': {
    summary: 'Logarithms as the reverse of indices, and the laws used to simplify and solve with them.',
    notes: [
      n('Definition',
        'If a^b = c, then log_a c = b, for a > 0, a ≠ 1 and c > 0. Example: 2³ = 8, so log₂ 8 = 3.',
        'log_a 1 = 0 and log_a a = 1.',
        'Logarithms of zero and of negative numbers are not defined.',
        'Common logarithms have base 10 and are written log x.'),
      n('Laws',
        'Product: log(mn) = log m + log n.',
        'Quotient: log(m/n) = log m − log n.',
        'Power: log(m^n) = n log m.'),
      n('Common mistakes',
        'log(m + n) is not log m + log n.',
        'log m / log n is not log(m/n).',
        '(log m)^n is not n log m.'),
      n('Using logarithms',
        'To expand, apply the laws term by term: log(a²b/c) = 2 log a + log b − log c.',
        'To solve, bring both sides to a single logarithm of the same base and compare.'),
    ] },
  'icse-triangles-congruency-in-triangles': {
    summary: 'Congruent triangles and the conditions that prove congruence.',
    notes: [
      n('Meaning',
        'Two triangles are congruent when they have the same shape and size: corresponding sides and corresponding angles are equal.',
        'Write the vertices in matching order: △ABC ≅ △PQR means A ↔ P, B ↔ Q and C ↔ R.'),
      n('Conditions',
        'SAS: two sides and the included angle.',
        'ASA: two angles and the included side. AAS: two angles and a corresponding side.',
        'SSS: three sides.',
        'RHS: right angle, hypotenuse and one side.'),
      n('What does not work',
        'AAA gives the same shape but not the same size.',
        'SSA (two sides and an angle that is not included) does not prove congruence.'),
      n('Using congruence',
        'Corresponding parts of congruent triangles are equal (c.p.c.t.).',
        'State the three equal pairs with reasons, then the condition used.'),
    ] },
  'icse-isosceles-triangles': {
    summary: 'Properties of isosceles and equilateral triangles.',
    notes: [
      n('Theorems',
        'Angles opposite equal sides of a triangle are equal.',
        'Conversely, sides opposite equal angles are equal.'),
      n('Consequences',
        'Each angle of an equilateral triangle is 60°.',
        'In an isosceles triangle, the bisector of the vertical angle, the altitude and the median to the base are the same line.',
        'A triangle with two equal altitudes or two equal medians is isosceles.'),
      n('Problem tips',
        'Mark the equal sides and the equal angles first.',
        'Use the angle sum 180° and the exterior angle property together with the equal angles.'),
    ] },
  'icse-inequalities': {
    summary: 'Relations between unequal sides and angles of a triangle.',
    notes: [
      n('Sides and angles',
        'If two sides of a triangle are unequal, the greater side has the greater angle opposite to it.',
        'Conversely, the greater angle has the greater side opposite to it.',
        'In a right-angled triangle the hypotenuse is the longest side.'),
      n('Triangle inequality',
        'The sum of any two sides of a triangle is greater than the third side.',
        'The difference of any two sides is less than the third side.'),
      n('Shortest distance',
        'Of all the segments from a point to a line, the perpendicular is the shortest.'),
    ] },
  'icse-mid-point-and-its-converse': {
    summary: 'The mid-point theorem, its converse and the intercept theorem.',
    notes: [
      n('Mid-point theorem',
        'The segment joining the midpoints of two sides of a triangle is parallel to the third side and equal to half of it.'),
      n('Converse',
        'A line drawn through the midpoint of one side of a triangle, parallel to another side, bisects the third side.'),
      n('Intercept theorem',
        'If a transversal makes equal intercepts on three or more parallel lines, then any other transversal also makes equal intercepts on them.'),
      n('Results',
        'The midpoints of the sides of any quadrilateral, joined in order, form a parallelogram.',
        'The three segments joining the midpoints of the sides of a triangle divide it into four congruent triangles.'),
    ] },
  'icse-pythagoras-theorem': {
    summary: 'Pythagoras theorem, its converse and applications.',
    notes: [
      n('Theorem',
        'In a right-angled triangle, hypotenuse² = sum of the squares of the other two sides.',
        'Converse: if the square on one side equals the sum of the squares on the other two, the angle opposite the first side is a right angle.'),
      n('Type of triangle',
        'With c the longest side: c² = a² + b² right-angled, c² < a² + b² acute-angled, c² > a² + b² obtuse-angled.'),
      n('Triples and uses',
        'Common triples: (3, 4, 5), (5, 12, 13), (8, 15, 17), (7, 24, 25).',
        'Diagonal of a rectangle = √(l² + b²). Altitude of an equilateral triangle of side a = (√3/2)a.',
        'In problems, draw a perpendicular to create right-angled triangles.'),
    ] },
  'icse-rectilinear-figures': {
    summary: 'Polygons and their angle sums, and the properties of parallelograms, rectangles, rhombuses, squares and trapeziums.',
    notes: [
      n('Polygons',
        'Sum of the interior angles of an n-sided polygon = (2n − 4) right angles.',
        'Sum of the exterior angles = 4 right angles (360°).',
        'Each interior angle of a regular polygon = (2n − 4) × 90° / n; each exterior angle = 360° / n.'),
      n('Parallelogram',
        'Opposite sides are equal, opposite angles are equal and the diagonals bisect each other.',
        'A quadrilateral is a parallelogram if one pair of opposite sides is equal and parallel.'),
      n('Special cases',
        'Rectangle: diagonals are equal. Rhombus: diagonals bisect at right angles and bisect the vertex angles.',
        'Square: diagonals are equal and bisect at right angles.',
        'Isosceles trapezium: base angles are equal and the diagonals are equal.'),
    ] },
  'icse-construction-of-polygons': {
    summary: 'Constructing quadrilaterals and regular polygons with ruler and compasses.',
    notes: [
      n('Quadrilaterals',
        'Draw a rough sketch, then build a triangle that can be drawn completely and locate the remaining vertex.',
        'Parallelogram: use the facts that opposite sides are equal and the diagonals bisect each other.',
        'Rhombus: the diagonals are perpendicular bisectors of each other. Square: one side or one diagonal is enough.'),
      n('Regular hexagon',
        'The side of a regular hexagon equals the radius of its circumscribing circle.',
        'Draw a circle with radius equal to the side, step the radius round the circle six times and join the points.',
        'Each interior angle is 120°.'),
      n('Good practice',
        'Use a sharp pencil, show all arcs and label every vertex.'),
    ] },
  'icse-area-theorems': {
    summary: 'Area relations between parallelograms and triangles on the same base and between the same parallels.',
    notes: [
      n('Parallelograms',
        'Parallelograms on the same base and between the same parallels are equal in area.',
        'A parallelogram and a rectangle on the same base and between the same parallels are equal in area.'),
      n('Triangles',
        'The area of a triangle is half that of a parallelogram on the same base and between the same parallels.',
        'Triangles on the same base and between the same parallels are equal in area.',
        'Triangles of equal area on the same base lie between the same parallels.'),
      n('Median',
        'A median divides a triangle into two triangles of equal area.',
        'Triangles with equal bases and the same height have equal areas.'),
    ] },
  'icse-circle': {
    summary: 'Chord properties of a circle and the relation between equal chords and arcs.',
    notes: [
      n('Chords',
        'The perpendicular from the centre to a chord bisects it. The line from the centre to the midpoint of a chord is perpendicular to it.',
        'Equal chords are equidistant from the centre; chords equidistant from the centre are equal.',
        'One and only one circle passes through three non-collinear points.'),
      n('Finding lengths',
        'With radius r, a chord of length 2a at distance d from the centre: r² = a² + d².',
        'For two parallel chords, the distance between them is the sum or the difference of their distances from the centre, depending on whether they are on opposite sides or the same side.'),
      n('Arcs and chords',
        'Equal chords cut off equal arcs, and equal arcs have equal chords.',
        'Equal arcs subtend equal angles at the centre.'),
    ] },
  'icse-statistics': {
    summary: 'Collecting and tabulating data, frequency distributions, and drawing histograms and frequency polygons.',
    notes: [
      n('Data',
        'Primary data is collected by the investigator; secondary data is taken from another source.',
        'A variable can be discrete (counted) or continuous (measured).'),
      n('Frequency distribution',
        'Class mark = (lower limit + upper limit)/2. Class size = difference between the true limits.',
        'Inclusive classes (10–19, 20–29) are made continuous by subtracting 0.5 from each lower limit and adding 0.5 to each upper limit.',
        'Cumulative frequency is the running total of the frequencies.'),
      n('Graphs',
        'Histogram: rectangles on continuous class intervals with heights equal to the frequencies and no gaps.',
        'Frequency polygon: join the midpoints of the tops of the histogram rectangles, or plot frequency against class mark, and close the polygon on the axis at both ends.'),
    ] },
  'icse-mean-and-median': {
    summary: 'Mean and median of ungrouped data and the properties of the mean.',
    notes: [
      n('Mean',
        'Mean = sum of the observations / number of observations.',
        'If every observation is increased, decreased, multiplied or divided by the same number, the mean changes in the same way.',
        'The sum of the deviations of the observations from their mean is zero.'),
      n('Median',
        'Arrange the data in ascending or descending order.',
        'For n observations with n odd, the median is the ((n + 1)/2)th observation.',
        'With n even, the median is the mean of the (n/2)th and (n/2 + 1)th observations.'),
      n('Finding unknowns',
        'Sum = mean × number of observations. Use this when a value is added, removed or corrected.'),
    ] },
  'icse-area-and-perimeter-of-plane-figures': {
    summary: 'Perimeter and area of triangles, quadrilaterals and circles.',
    notes: [
      n('Triangles',
        'Area = ½ × base × height.',
        'Heron’s formula: √[s(s − a)(s − b)(s − c)], with s = (a + b + c)/2.',
        'Equilateral triangle of side a: area = (√3/4)a², height = (√3/2)a.',
        'Isosceles triangle with equal sides a and base b: area = (b/4)√(4a² − b²).'),
      n('Quadrilaterals',
        'Rectangle: area = lb, perimeter = 2(l + b), diagonal = √(l² + b²).',
        'Square of side a: area = a² = ½ × diagonal², perimeter = 4a.',
        'Parallelogram: base × height. Rhombus: ½ × product of the diagonals. Trapezium: ½ × (sum of the parallel sides) × height.'),
      n('Circle',
        'Circumference = 2πr. Area = πr².',
        'Area of a ring = π(R² − r²).',
        'Distance covered by a wheel in one revolution = its circumference.'),
    ] },
  'icse-solids': {
    summary: 'Surface area and volume of cuboids and cubes, cross-sections and the flow of water.',
    notes: [
      n('Cuboid and cube',
        'Cuboid: volume = lbh, total surface area = 2(lb + bh + hl), diagonal = √(l² + b² + h²).',
        'Cube of side a: volume = a³, total surface area = 6a², diagonal = a√3.',
        'Area of the four walls of a room = 2(l + b)h.'),
      n('Cross-section',
        'For a solid with a uniform cross-section: volume = area of cross-section × length.',
        'Surface area excluding the ends = perimeter of cross-section × length.'),
      n('Flow of water',
        'Volume of water flowing in unit time = area of cross-section of the pipe × speed of the water.',
        'Keep the units consistent: change km/h to m/s or cm/s as needed.'),
      n('Units',
        '1 m³ = 1000 litres. 1 litre = 1000 cm³.'),
    ] },
  'icse-trigonometrical-ratios': {
    summary: 'The six trigonometrical ratios of an acute angle and the relations between them.',
    notes: [
      n('Ratios',
        'For an acute angle A in a right-angled triangle: sin A = perpendicular/hypotenuse, cos A = base/hypotenuse, tan A = perpendicular/base.',
        'cosec A = 1/sin A, sec A = 1/cos A, cot A = 1/tan A.',
        'tan A = sin A / cos A and cot A = cos A / sin A.'),
      n('Relations',
        'sin²A + cos²A = 1.',
        '1 + tan²A = sec²A.',
        '1 + cot²A = cosec²A.'),
      n('Method',
        'Given one ratio, draw a right-angled triangle with sides in that ratio, find the third side by Pythagoras theorem, then read off the other ratios.',
        'The value of a ratio depends only on the angle, not on the size of the triangle.'),
    ] },
  'icse-trigonometrical-ratios-of-standard-angles': {
    summary: 'Values of the trigonometrical ratios for 0°, 30°, 45°, 60° and 90°, and their use.',
    notes: [
      n('Values',
        'sin 0° = 0, sin 30° = ½, sin 45° = 1/√2, sin 60° = √3/2, sin 90° = 1.',
        'cos 0° = 1, cos 30° = √3/2, cos 45° = 1/√2, cos 60° = ½, cos 90° = 0.',
        'tan 0° = 0, tan 30° = 1/√3, tan 45° = 1, tan 60° = √3, tan 90° is not defined.'),
      n('Patterns',
        'As the angle goes from 0° to 90°, sin increases from 0 to 1 and cos decreases from 1 to 0.',
        'The values of cos are the values of sin in reverse order.'),
      n('Using the values',
        'Evaluate expressions by substituting the values.',
        'To solve an equation such as 2 sin A = 1, find the ratio first (sin A = ½), then the angle (A = 30°).',
        'sin 2A is not 2 sin A: sin 60° = √3/2, but 2 sin 30° = 1.'),
    ] },
  'icse-solution-of-right-triangles': {
    summary: 'Finding unknown sides and angles of right-angled triangles using trigonometrical ratios.',
    notes: [
      n('Method',
        'Mark the known side and the side to be found relative to the given angle: perpendicular (opposite), base (adjacent) or hypotenuse.',
        'Choose the ratio that connects these two sides: sin for opposite and hypotenuse, cos for adjacent and hypotenuse, tan for opposite and adjacent.',
        'Form the equation and solve.'),
      n('Figures that are not right triangles',
        'Draw a perpendicular to split the figure into right-angled triangles.',
        'Find a common side first; it links the two triangles.'),
      n('Example',
        'In a right-angled triangle with an angle of 30° and hypotenuse 20 cm, the side opposite 30° is 20 × sin 30° = 10 cm and the adjacent side is 20 × cos 30° = 10√3 cm.'),
    ] },
  'icse-complementary-angles': {
    summary: 'Trigonometrical ratios of complementary angles.',
    notes: [
      n('Relations',
        'Two angles are complementary when their sum is 90°.',
        'sin(90° − A) = cos A and cos(90° − A) = sin A.',
        'tan(90° − A) = cot A and cot(90° − A) = tan A.',
        'sec(90° − A) = cosec A and cosec(90° − A) = sec A.'),
      n('Using them',
        'Change one ratio so that both angles match. Example: sin 35° / cos 55° = sin 35° / sin 35° = 1.',
        'tan 20° × tan 70° = tan 20° × cot 20° = 1.',
        'If sin A = cos B for acute angles A and B, then A + B = 90°.'),
    ] },
  'icse-co-ordinate-geometry': {
    summary: 'Coordinates, graphs of linear equations, and the slope and intercept of a line.',
    notes: [
      n('Coordinates',
        'A point is located by an ordered pair (x, y): x is the abscissa and y is the ordinate.',
        'Signs in the four quadrants: I (+, +), II (−, +), III (−, −), IV (+, −).',
        'On the x-axis y = 0; on the y-axis x = 0.'),
      n('Graphs of straight lines',
        'x = a is a line parallel to the y-axis. y = b is a line parallel to the x-axis.',
        'For any other linear equation, make a table of three points, plot them and join.'),
      n('Slope and intercept',
        'In y = mx + c, m is the slope and c is the y-intercept.',
        'Slope m = tan θ, where θ is the angle the line makes with the positive direction of the x-axis (its inclination).',
        'To read m and c from an equation such as 2x + 3y = 6, first write it as y = −(2/3)x + 2.'),
    ] },
  'icse-graphical-solution': {
    summary: 'Solving simultaneous linear equations by drawing their graphs.',
    notes: [
      n('Method',
        'Draw the graphs of both equations on the same axes with the same scale.',
        'The coordinates of the point where the lines meet give the solution.',
        'Check the answer by substituting in both equations.'),
      n('Types of solution',
        'Lines that intersect: one solution.',
        'Parallel lines: no solution.',
        'Coincident lines: infinitely many solutions.'),
      n('Tips',
        'Choose values of x that give whole-number values of y where possible.',
        'State the scale used on each axis.'),
    ] },
  'icse-distance-formula': {
    summary: 'The distance between two points and its use in identifying figures.',
    notes: [
      n('Formula',
        'Distance between (x₁, y₁) and (x₂, y₂) = √[(x₂ − x₁)² + (y₂ − y₁)²].',
        'Distance of (x, y) from the origin = √(x² + y²).'),
      n('Applications',
        'Three points A, B, C are collinear if the sum of two of the distances AB, BC, CA equals the third.',
        'Triangle type: compare the three sides; for a right angle check Pythagoras theorem.',
        'Quadrilateral: four equal sides give a rhombus, and equal diagonals as well give a square; opposite sides equal give a parallelogram, and equal diagonals as well give a rectangle.'),
      n('Finding a point',
        'A point on the x-axis is (x, 0) and a point on the y-axis is (0, y).',
        'A point equidistant from two given points: equate the two distances, square both sides and solve.',
        'The circumcentre of a triangle is equidistant from its three vertices.'),
    ] },
};
