// Topic-wise notes for Class 8, keyed by chapter slug. n(topic, ...points) makes one topic.
const n = (topic, ...points) => ({ topic, points });

const DIVISIBILITY = n('Tests of divisibility',
  'By 2: the last digit is even. By 5: the last digit is 0 or 5. By 10: the last digit is 0.',
  'By 4: the number formed by the last two digits is divisible by 4. By 8: the number formed by the last three digits is divisible by 8.',
  'By 3: the sum of the digits is divisible by 3. By 9: the sum of the digits is divisible by 9.',
  'By 6: the number is divisible by both 2 and 3.',
  'By 11: the difference between the sum of the digits in odd places and the sum of the digits in even places is 0 or a multiple of 11.');

export default {
  // ---------- CBSE: Ganita Prakash ----------
  'a-square-and-a-cube': {
    summary: 'Square numbers, cube numbers and their roots, with the patterns that help you spot and find them.',
    notes: [
      n('Square numbers',
        'A square number is a number multiplied by itself: n² = n × n. Examples: 1, 4, 9, 16, 25.',
        'A perfect square ends only in 0, 1, 4, 5, 6 or 9. A number ending in 2, 3, 7 or 8 is never a perfect square.',
        'The sum of the first n odd numbers is n². Example: 1 + 3 + 5 + 7 = 16 = 4².',
        'A perfect square ends in an even number of zeros.'),
      n('Square roots',
        'If n² = m, then n is the square root of m, written √m. Example: √49 = 7.',
        'Prime factorisation method: write the number as a product of primes, pair equal primes and take one from each pair. Example: 324 = 2 × 2 × 3 × 3 × 3 × 3, so √324 = 2 × 3 × 3 = 18.',
        'If a prime factor is left without a pair, the number is not a perfect square.',
        'Estimate first: √200 lies between 14 and 15, because 14² = 196 and 15² = 225.'),
      n('Cube numbers',
        'A cube number is n³ = n × n × n. Examples: 1, 8, 27, 64, 125.',
        'The cube of an even number is even and the cube of an odd number is odd.',
        'In the prime factorisation of a perfect cube, every prime appears in groups of three.',
        '1729 is the smallest number that is a sum of two cubes in two different ways: 1³ + 12³ = 9³ + 10³.'),
      n('Cube roots',
        'If n³ = m, then n is the cube root of m, written ∛m. Example: ∛216 = 6.',
        'Prime factorisation method: group equal primes in threes and take one from each group. Example: 1728 = 2⁶ × 3³, so ∛1728 = 2 × 2 × 3 = 12.'),
    ] },
  'power-play': {
    summary: 'Exponents and their laws, powers of 10, scientific notation and how quickly exponential growth builds up.',
    notes: [
      n('Exponential notation',
        'a^n means a multiplied by itself n times. a is the base and n is the exponent. Example: 2⁵ = 2 × 2 × 2 × 2 × 2 = 32.',
        'a¹ = a and, for a ≠ 0, a⁰ = 1.',
        '(−1) raised to an even power is 1; raised to an odd power it is −1.'),
      n('Laws of exponents',
        'a^m × a^n = a^(m+n)',
        'a^m ÷ a^n = a^(m−n), for a ≠ 0',
        '(a^m)^n = a^(mn)',
        '(ab)^m = a^m × b^m and (a/b)^m = a^m / b^m'),
      n('Negative exponents',
        'a^(−n) = 1 / a^n for a ≠ 0. Example: 2^(−3) = 1/8.',
        'The laws of exponents work for negative exponents as well.'),
      n('Powers of 10 and scientific notation',
        'A number in scientific notation is written as k × 10^n, where 1 ≤ k < 10. Example: 59,800 = 5.98 × 10⁴.',
        'Small numbers use negative powers: 0.0007 = 7 × 10^(−4).',
        'To compare two numbers in scientific notation, compare the powers of 10 first.'),
      n('Linear and exponential growth',
        'Linear growth adds the same amount at each step: 3, 6, 9, 12.',
        'Exponential growth multiplies by the same number at each step: 3, 9, 27, 81. It soon becomes far larger than linear growth.',
        'Doubling something 10 times multiplies it by 2¹⁰ = 1024.'),
    ] },
  'a-story-of-numbers': {
    summary: 'How people counted and wrote numbers through history, and why the place value system with zero is so powerful.',
    notes: [
      n('Early ways of counting',
        'The earliest counting matched objects one to one with tally marks, pebbles or notches on a bone.',
        'Grouping the marks, for example in fives or tens, made large counts easier to read.'),
      n('Number systems of different civilisations',
        'Egyptian: a separate symbol for 1, 10, 100, 1000 and so on, repeated as needed. Base 10, but no place value.',
        'Roman: letters I (1), V (5), X (10), L (50), C (100), D (500), M (1000). A smaller symbol before a larger one is subtracted: IV = 4, IX = 9.',
        'Mesopotamian (Babylonian): base 60 with place value. We still use 60 in minutes and seconds.',
        'Mayan: base 20, with a symbol for zero.',
        'Chinese: rod numerals with place value in base 10.'),
      n('The Hindu-Arabic system',
        'It uses only ten digits, 0 to 9, and the value of a digit depends on its place.',
        'Zero works both as a placeholder and as a number. This idea was developed in India.',
        'The system travelled from India to the Arab world and then to Europe, and is used all over the world today.'),
      n('Why place value matters',
        'Any number, however large, can be written with the same ten digits.',
        'Addition, subtraction, multiplication and division become simple column methods. Compare adding 48 + 37 with adding XLVIII + XXXVII.',
        'The base tells how many units make the next place: base 10 groups in tens, base 2 in twos, base 60 in sixties.'),
    ] },
  'quadrilaterals': {
    summary: 'Types of quadrilaterals and the properties of their sides, angles and diagonals.',
    notes: [
      n('Basics',
        'A quadrilateral has 4 sides, 4 angles and 2 diagonals.',
        'The sum of the interior angles of a quadrilateral is 360°.'),
      n('Parallelogram',
        'Both pairs of opposite sides are parallel.',
        'Opposite sides are equal and opposite angles are equal.',
        'Adjacent angles add up to 180°.',
        'The diagonals bisect each other.'),
      n('Rectangle, rhombus and square',
        'Rectangle: a parallelogram with four right angles. Its diagonals are equal and bisect each other.',
        'Rhombus: a parallelogram with four equal sides. Its diagonals bisect each other at right angles.',
        'Square: a rectangle with equal sides, and also a rhombus with right angles. Its diagonals are equal and bisect each other at right angles.'),
      n('Trapezium and kite',
        'Trapezium: a quadrilateral with one pair of opposite sides parallel.',
        'Isosceles trapezium: the non-parallel sides are equal, and so are the angles on each parallel side.',
        'Kite: two pairs of equal adjacent sides. One diagonal is the perpendicular bisector of the other.'),
      n('How the shapes are related',
        'Every square is a rectangle and also a rhombus.',
        'Every rectangle and every rhombus is a parallelogram.',
        'To prove a property, split the quadrilateral into two triangles with a diagonal and use congruence.'),
    ] },
  'number-play': {
    summary: 'Patterns in numbers: odd and even (parity), sums of consecutive numbers and divisibility rules, used to solve number puzzles.',
    notes: [
      n('Parity (odd and even)',
        'even + even = even, odd + odd = even, even + odd = odd.',
        'even × any whole number = even, odd × odd = odd.',
        'A sum of several numbers is odd only when it contains an odd count of odd numbers.'),
      n('Sums of consecutive numbers',
        'The sum of two consecutive numbers is always odd.',
        'The sum of three consecutive numbers is always a multiple of 3: (n − 1) + n + (n + 1) = 3n.',
        'Every odd number greater than 1 is a sum of two consecutive numbers: 2n + 1 = n + (n + 1).',
        'Powers of 2 (2, 4, 8, 16, ...) cannot be written as a sum of two or more consecutive natural numbers.'),
      n('Divisibility rules', ...DIVISIBILITY.points),
      n('Why the rules work',
        'A two-digit number with digits a and b is 10a + b; a three-digit number is 100a + 10b + c.',
        '100a + 10b + c = 99a + 9b + (a + b + c), so the remainder on dividing by 9 (or by 3) is the same as that of the digit sum.',
        'Use the same idea to solve digit puzzles in which letters stand for digits.'),
    ] },
  'we-distribute-yet-things-multiply': {
    summary: 'The distributive property, multiplying algebraic expressions and the three standard identities, with their use in quick calculation.',
    notes: [
      n('The distributive property',
        'a(b + c) = ab + ac and a(b − c) = ab − ac.',
        'It explains ordinary multiplication: 23 × 7 = (20 + 3) × 7 = 140 + 21 = 161.',
        'Read backwards it takes out a common factor: ab + ac = a(b + c).'),
      n('Multiplying expressions',
        '(a + b)(c + d) = ac + ad + bc + bd: every term of the first bracket multiplies every term of the second.',
        'Multiply the signs carefully: (−) × (−) = (+) and (−) × (+) = (−).',
        'After multiplying, combine the like terms.'),
      n('Standard identities',
        '(a + b)² = a² + 2ab + b²',
        '(a − b)² = a² − 2ab + b²',
        '(a + b)(a − b) = a² − b²',
        'An identity is true for every value of the letters, unlike an equation.'),
      n('Quick calculations',
        '103² = (100 + 3)² = 10000 + 600 + 9 = 10609.',
        '98² = (100 − 2)² = 10000 − 400 + 4 = 9604.',
        '47 × 53 = (50 − 3)(50 + 3) = 2500 − 9 = 2491.'),
    ] },
  'proportional-reasoning-1': {
    summary: 'Ratios, proportion and the unit method, used to compare quantities and to scale them up or down.',
    notes: [
      n('Ratio',
        'A ratio a : b compares two quantities of the same kind measured in the same unit.',
        'Multiplying or dividing both terms by the same non-zero number gives an equivalent ratio: 6 : 9 = 2 : 3.',
        'A ratio in simplest form has terms with no common factor other than 1.'),
      n('Proportion',
        'Four numbers are in proportion when a : b = c : d.',
        'Cross-multiplication: if a : b = c : d, then a × d = b × c.',
        'Example: 3 : 5 = x : 20 gives 5x = 60, so x = 12.'),
      n('Unit method',
        'Find the value for one unit, then multiply. Example: if 5 pens cost ₹60, then 1 pen costs ₹12 and 8 pens cost ₹96.',
        'Two quantities are proportional when their ratio stays the same as both change.'),
      n('Sharing in a ratio',
        'To divide a quantity in the ratio a : b, the parts are a/(a + b) and b/(a + b) of the whole.',
        'Example: ₹700 in the ratio 3 : 4 gives ₹300 and ₹400.'),
      n('Common mistakes',
        'Convert to the same unit before writing a ratio: 50 cm to 2 m is 50 : 200 = 1 : 4.',
        'The order matters: 2 : 3 is not the same as 3 : 2.'),
    ] },
  'fractions-in-disguise': {
    summary: 'Percentages as fractions with denominator 100: converting, finding a percentage of a quantity, and percentage change.',
    notes: [
      n('Meaning of per cent',
        'Per cent means out of 100: 35% = 35/100 = 0.35.',
        'Fraction to percentage: multiply by 100. Example: 3/8 = 37.5%.',
        'Percentage to fraction: write it over 100 and simplify. Example: 45% = 9/20.'),
      n('Percentage of a quantity',
        'x% of a quantity = (x/100) × quantity. Example: 15% of 240 = 36.',
        'What per cent is a of b? (a/b) × 100. Example: 18 out of 72 is 25%.',
        'Finding the whole: if 30% of a number is 45, the number is 45 × 100 / 30 = 150.'),
      n('Percentage change',
        'Percentage change = (change / original value) × 100.',
        'To increase a quantity by x%, multiply by (1 + x/100). To decrease it by x%, multiply by (1 − x/100).',
        'An increase of 10% followed by a decrease of 10% does not return to the start: 100 → 110 → 99.'),
      n('Everyday uses',
        'Profit % and loss % are calculated on the cost price.',
        'Discount % is calculated on the marked price.',
        'Percentages make a comparison fair when the totals are different, for example marks out of different maximums.'),
    ] },
  'baudhayana-pythagoras-theorem': {
    summary: 'The relation between the sides of a right-angled triangle, its converse, and how to use it to find lengths.',
    notes: [
      n('The theorem',
        'In a right-angled triangle, the square on the hypotenuse equals the sum of the squares on the other two sides: a² + b² = c².',
        'The hypotenuse is the side opposite the right angle and is the longest side.',
        'Baudhayana stated this result in the Sulba-sutras, centuries before Pythagoras.'),
      n('Finding a side',
        'Hypotenuse: c = √(a² + b²). Example: sides 6 and 8 give c = √100 = 10.',
        'Other side: a = √(c² − b²). Example: hypotenuse 13 and side 5 give √144 = 12.',
        'The diagonal of a square of side a is a√2. The diagonal of a rectangle is √(l² + b²).'),
      n('Baudhayana-Pythagoras triples',
        'Three whole numbers with a² + b² = c² form a triple: (3, 4, 5), (5, 12, 13), (8, 15, 17), (7, 24, 25).',
        'Any multiple of a triple is also a triple: (6, 8, 10), (9, 12, 15).'),
      n('The converse',
        'If the sides of a triangle satisfy a² + b² = c², the angle opposite side c is a right angle.',
        'Use it to test for a right angle: sides 9, 40, 41 give 81 + 1600 = 1681 = 41², so the triangle is right-angled.'),
      n('Squares and the diagonal',
        'The square drawn on the diagonal of a square has twice the area of the original square.',
        'The diagonal of a unit square has length √2, which cannot be written as a fraction.'),
    ] },
  'proportional-reasoning-2': {
    summary: 'Ratios with more than two terms, scales on maps, and direct and inverse proportion.',
    notes: [
      n('Direct proportion',
        'x and y are in direct proportion when x/y stays constant: as one doubles, the other doubles.',
        'x₁/y₁ = x₂/y₂. Example: if 4 kg costs ₹180, then 10 kg costs ₹450.'),
      n('Maps and scale',
        'A scale of 1 : 50,000 means 1 cm on the map stands for 50,000 cm = 500 m on the ground.',
        'Actual distance = map distance × scale factor. Keep the units the same before converting.'),
      n('Ratios with three or more terms',
        'a : b : c compares three quantities at once. The parts are a, b and c out of a + b + c.',
        'Example: ₹1200 in the ratio 1 : 2 : 3 gives ₹200, ₹400 and ₹600.',
        'To join a : b and b : c, make the b terms equal. Example: 2 : 3 and 4 : 5 give 8 : 12 : 15.'),
      n('Inverse proportion',
        'x and y are in inverse proportion when the product xy stays constant: as one doubles, the other halves.',
        'x₁y₁ = x₂y₂. Example: 6 workers take 10 days, so 15 workers take 6 × 10 / 15 = 4 days.',
        'Speed and time for a fixed distance are in inverse proportion.'),
      n('Which one is it?',
        'More of one giving more of the other in the same ratio is direct proportion.',
        'More of one giving less of the other with a constant product is inverse proportion.',
        'Some pairs are neither, for example age and height.'),
    ] },
  'exploring-some-geometric-themes': {
    summary: 'Fractals built by repeating a rule, and ways of seeing and drawing three-dimensional solids.',
    notes: [
      n('Fractals',
        'A fractal is a shape made by repeating the same rule again and again. Small parts look like the whole shape (self-similarity).',
        'Sierpinski triangle: join the midpoints of the sides of an equilateral triangle and remove the middle triangle; repeat on each remaining triangle. Each step multiplies the number of triangles by 3 and the area by 3/4.',
        'Koch snowflake: replace the middle third of every side with two sides of a small equilateral triangle. Each step multiplies the perimeter by 4/3.'),
      n('Solids',
        'A polyhedron has flat faces, straight edges and vertices. Prisms and pyramids are polyhedra; cylinders, cones and spheres are not.',
        'Euler’s formula for polyhedra: F + V − E = 2. A cube has 6 faces, 8 vertices and 12 edges: 6 + 8 − 12 = 2.'),
      n('Nets',
        'A net is a flat pattern that folds into a solid.',
        'A cube has 6 square faces and 11 different nets.',
        'Opposite faces of the solid never share an edge in the net.'),
      n('Views and projections',
        'A solid can be shown by its front view, side view and top view.',
        'Different solids can look the same from one direction, so more than one view is needed.',
        'A drawing on isometric dot paper shows three faces of a solid at once.'),
    ] },
  'tales-by-dots-and-lines': {
    summary: 'Describing data with a single value using the mean and the median, and reading data from tables and plots.',
    notes: [
      n('Mean',
        'Mean = sum of all the values ÷ number of values.',
        'Example: 4, 7, 9, 10, 15 has mean 45 ÷ 5 = 9.',
        'The mean is the balance point: the total distance of the values below it equals the total distance of the values above it.',
        'Adding the same number to every value adds that number to the mean; multiplying every value by a number multiplies the mean by it.'),
      n('Median',
        'Arrange the data in order. The median is the middle value.',
        'For an odd number of values it is the middle one; for an even number it is the mean of the two middle values.',
        'Example: 3, 5, 8, 12 has median (5 + 8) ÷ 2 = 6.5.'),
      n('Mean or median?',
        'One very large or very small value (an outlier) pulls the mean but hardly moves the median.',
        'For data such as incomes or house prices, the median often describes a typical value better.'),
      n('Data in a frequency table',
        'Mean = sum of (value × frequency) ÷ sum of the frequencies.',
        'For the median, count through the frequencies to reach the middle position.'),
      n('Finding a missing value',
        'Sum of the values = mean × number of values.',
        'Example: five values have mean 12, and four of them add up to 46. The fifth is 60 − 46 = 14.'),
      n('Dot plots and line graphs',
        'A dot plot shows each value as a dot above a number line, so clusters, gaps and the middle are easy to see.',
        'A line graph joins points to show how a quantity changes over time.'),
    ] },
  'algebra-play': {
    summary: 'Using algebra to explain number tricks, patterns and puzzles.',
    notes: [
      n('Why number tricks work',
        'Call the unknown number x and follow the steps. Example: think of a number, double it, add 6, halve it, subtract the original number. (2x + 6)/2 − x = 3, so the answer is always 3.',
        'If the final expression has no x in it, the result is the same for every starting number.'),
      n('Digits and place value',
        'A two-digit number with tens digit a and units digit b is 10a + b. Its reverse is 10b + a.',
        'The sum of a number and its reverse is 11(a + b), always a multiple of 11.',
        'The difference of a number and its reverse is 9(a − b), always a multiple of 9.'),
      n('Calendar and grid patterns',
        'In a calendar, the number below any date is 7 more, and the number to its right is 1 more.',
        'In any 2 × 2 block of dates a, a + 1, a + 7, a + 8, the two diagonal sums are equal: both are 2a + 8.',
        'In a 3 × 3 block the sum of all nine dates is 9 times the middle date.'),
      n('Number pyramids',
        'In an addition pyramid each brick is the sum of the two bricks below it.',
        'With bottom row a, b, c the top brick is a + 2b + c, so the middle number counts twice.'),
      n('Largest product',
        'For two numbers with a fixed sum, the product is largest when the numbers are equal or as close as possible.',
        'Example: for a sum of 20, 10 × 10 = 100 is larger than 9 × 11 = 99 or 8 × 12 = 96, because (10 − d)(10 + d) = 100 − d².'),
    ] },
  'area': {
    summary: 'Area formulas for triangles and quadrilaterals, and how to find the area of any polygon by splitting it up.',
    notes: [
      n('Rectangle, square and parallelogram',
        'Rectangle: area = length × breadth. Square: area = side².',
        'Parallelogram: area = base × height, where the height is the perpendicular distance between the base and the opposite side.',
        'Cutting a triangle off one end of a parallelogram and moving it to the other end gives a rectangle with the same base and height.'),
      n('Triangle',
        'Area = ½ × base × height.',
        'A diagonal divides a parallelogram into two triangles of equal area.',
        'Triangles on the same base and between the same parallel lines have equal area.'),
      n('Trapezium and rhombus',
        'Trapezium: area = ½ × (sum of the parallel sides) × height.',
        'Rhombus: area = ½ × product of the diagonals. The same formula works for a kite.'),
      n('Any polygon',
        'Divide the polygon into triangles, rectangles and trapeziums, find each area and add.',
        'On a square grid, count the full squares and combine part squares to estimate the area.'),
      n('Units',
        '1 m² = 10,000 cm². 1 hectare = 10,000 m². 1 km² = 100 hectares.',
        'Always write area in square units.'),
    ] },

  // ---------- ICSE: Selina Concise Mathematics ----------
  'icse-rational-numbers': {
    summary: 'Rational numbers, their properties under the four operations, and how to place them on a number line.',
    notes: [
      n('Definition',
        'A rational number can be written as p/q, where p and q are integers and q ≠ 0.',
        'Every integer and every fraction is a rational number. Zero is a rational number.',
        'Standard form: the denominator is positive, and the numerator and denominator have no common factor.'),
      n('Operations',
        'Add or subtract by taking the LCM of the denominators.',
        'Multiply: (a/b) × (c/d) = ac/bd. Divide: multiply by the reciprocal.',
        'The additive inverse of a/b is −a/b. The multiplicative inverse (reciprocal) of a/b is b/a, for a ≠ 0.'),
      n('Properties',
        'Closure: the sum, difference and product of two rational numbers are rational.',
        'Addition and multiplication are commutative and associative; subtraction and division are not.',
        'Distributive property: a(b + c) = ab + ac.',
        '0 is the additive identity and 1 is the multiplicative identity.'),
      n('Number line and numbers in between',
        'To mark p/q, divide each unit into q equal parts.',
        'Between any two rational numbers there are infinitely many rational numbers. One of them is their mean, (a + b)/2.'),
    ] },
  'icse-exponents-powers': {
    summary: 'Positive, zero and negative exponents and the laws for working with them.',
    notes: [
      n('Meaning',
        'a^n = a × a × ... × a (n times). a is the base and n is the exponent.',
        'a⁰ = 1 for a ≠ 0. a^(−n) = 1 / a^n.',
        '(a/b)^(−n) = (b/a)^n.'),
      n('Laws of exponents',
        'a^m × a^n = a^(m+n)',
        'a^m ÷ a^n = a^(m−n)',
        '(a^m)^n = a^(mn)',
        '(ab)^n = a^n × b^n and (a/b)^n = a^n / b^n'),
      n('Using the laws',
        'Write every number as a power of a prime before simplifying. Example: 8² × 4³ = 2⁶ × 2⁶ = 2¹².',
        'If a^x = a^y, with a not equal to 0, 1 or −1, then x = y. Use this to find an unknown exponent.'),
    ] },
  'icse-squares-and-square-roots': {
    summary: 'Perfect squares, their properties, and finding square roots by prime factorisation and by division.',
    notes: [
      n('Perfect squares',
        'A perfect square is the square of a whole number: 1, 4, 9, 16, 25, ...',
        'A perfect square never ends in 2, 3, 7 or 8, and ends in an even number of zeros.',
        'The square of an even number is even and the square of an odd number is odd.',
        'The sum of the first n odd numbers is n².'),
      n('Square root by prime factorisation',
        'Write the number as a product of primes, make pairs of equal primes and take one from each pair.',
        'Example: 1764 = 2 × 2 × 3 × 3 × 7 × 7, so √1764 = 2 × 3 × 7 = 42.',
        'To make a number a perfect square, multiply or divide by the primes that are left unpaired.'),
      n('Square root by division',
        'Pair the digits from the units place. Find the largest square not greater than the first pair, subtract, bring down the next pair, and use twice the quotient as the trial divisor.',
        'For decimals, pair the digits on both sides starting from the decimal point.',
        'Example: √1296 = 36.'),
      n('Useful results',
        '√(a × b) = √a × √b and √(a/b) = √a / √b.',
        'The square root of a number with 2n or 2n − 1 digits has n digits.'),
    ] },
  'icse-cubes-and-cube-roots': {
    summary: 'Perfect cubes and finding cube roots by prime factorisation.',
    notes: [
      n('Cubes',
        'n³ = n × n × n. Cubes of 1 to 10: 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000.',
        'The cube of a negative number is negative: (−4)³ = −64.',
        'In a perfect cube every prime factor occurs three times or a multiple of three times.'),
      n('Cube roots',
        'Group the prime factors in threes and take one factor from each group. Example: 3375 = 3³ × 5³, so ∛3375 = 15.',
        '∛(−a) = −∛a and ∛(a × b) = ∛a × ∛b.'),
      n('Making a perfect cube',
        'To find the smallest number to multiply or divide by, look for the prime factors that do not form a complete group of three.',
        'Example: 108 = 2² × 3³. Multiply by 2 to get 216 = 6³.'),
    ] },
  'icse-playing-with-numbers': {
    summary: 'Numbers in general form, digit puzzles and tests of divisibility.',
    notes: [
      n('General form',
        'A two-digit number with digits a and b is 10a + b. A three-digit number is 100a + 10b + c.',
        'The sum of a two-digit number and its reverse is 11(a + b). Their difference is 9(a − b).'),
      n('Letters for digits',
        'Each letter stands for one digit, and different letters stand for different digits.',
        'The first digit of a number cannot be zero. Start with the column that gives the most information, usually the units column.'),
      DIVISIBILITY,
    ] },
  'icse-sets': {
    summary: 'Sets, the ways of writing them, types of sets, and union, intersection and Venn diagrams.',
    notes: [
      n('Writing a set',
        'A set is a well-defined collection of objects, called elements. a ∈ A means a is an element of A.',
        'Roster form lists the elements: A = {2, 4, 6, 8}. Set-builder form gives the rule: A = {x : x is an even natural number less than 10}.',
        'n(A) is the number of elements in A, called its cardinal number.'),
      n('Types of sets',
        'Empty set: a set with no elements, written { } or ∅. A set is finite or infinite.',
        'Equal sets have exactly the same elements. Equivalent sets have the same number of elements.',
        'A ⊆ B means every element of A is in B. A set with n elements has 2^n subsets.',
        'The universal set is the set of all elements under discussion.'),
      n('Operations',
        'Union A ∪ B: elements in A or in B or in both.',
        'Intersection A ∩ B: elements common to A and B. Disjoint sets have no common element.',
        'Difference A − B: elements of A that are not in B. Complement A′: elements of the universal set that are not in A.'),
      n('Venn diagrams and counting',
        'n(A ∪ B) = n(A) + n(B) − n(A ∩ B).',
        'Draw the universal set as a rectangle and the sets as circles; fill in the common region first.'),
    ] },
  'icse-percent-and-percentage': {
    summary: 'Percentages, converting between fractions, decimals and percentages, and percentage increase and decrease.',
    notes: [
      n('Conversions',
        'Per cent means out of 100: 35% = 35/100 = 0.35.',
        'Fraction or decimal to percentage: multiply by 100. Example: 3/8 = 37.5%.',
        'Percentage to fraction: divide by 100 and simplify. Example: 45% = 9/20.'),
      n('Percentage of a quantity',
        'x% of a quantity = (x/100) × quantity.',
        'To express a as a percentage of b: (a/b) × 100. Both must be in the same unit.',
        'If x% of a number is known, the number = known value × 100 / x.'),
      n('Increase and decrease',
        'Increase % = (increase / original value) × 100. Decrease % = (decrease / original value) × 100.',
        'New value after an increase of x% = original × (100 + x)/100; after a decrease of x% = original × (100 − x)/100.',
        'If A is x% more than B, then B is less than A by x/(100 + x) × 100 per cent, not x%.'),
    ] },
  'icse-profit-loss-and-discount': {
    summary: 'Cost price, selling price, profit and loss per cent, marked price and discount.',
    notes: [
      n('Profit and loss',
        'Profit = SP − CP when SP > CP. Loss = CP − SP when CP > SP.',
        'Profit % = (profit / CP) × 100. Loss % = (loss / CP) × 100.',
        'Overheads such as transport and repairs are added to the cost price.'),
      n('Finding SP or CP',
        'SP = CP × (100 + profit %) / 100, or CP × (100 − loss %) / 100.',
        'CP = SP × 100 / (100 + profit %), or SP × 100 / (100 − loss %).'),
      n('Discount',
        'Discount = marked price − selling price. Discount % = (discount / MP) × 100.',
        'SP = MP × (100 − discount %) / 100.',
        'Successive discounts of 20% and 10% are not 30%: the price becomes 0.8 × 0.9 = 0.72 of MP, a single discount of 28%.'),
    ] },
  'icse-simple-and-compound-interest': {
    summary: 'Simple interest and compound interest, and how they differ.',
    notes: [
      n('Simple interest',
        'SI = (P × R × T) / 100, where P is the principal, R the rate per cent per year and T the time in years.',
        'Amount A = P + SI.',
        'For a time given in months divide by 12; in days divide by 365.'),
      n('Compound interest',
        'Interest is added to the principal at the end of each period, so the next period’s interest is calculated on a larger sum.',
        'A = P(1 + R/100)^n for n years compounded yearly. CI = A − P.',
        'For the first year SI and CI are equal. For 2 years, CI − SI = P(R/100)².'),
      n('Working year by year',
        'Year 1: interest on P. Year 2: interest on P plus the first year’s interest, and so on.',
        'Example: ₹10,000 at 10% for 2 years. Year 1 interest ₹1,000; year 2 interest ₹1,100; CI = ₹2,100.'),
    ] },
  'icse-direct-and-inverse-variations': {
    summary: 'Direct and inverse variation, the unitary method, and time and work.',
    notes: [
      n('Direct variation',
        'x and y vary directly when x/y is constant: both increase or decrease in the same ratio.',
        'x₁/y₁ = x₂/y₂. Example: cost and number of articles at a fixed price.'),
      n('Inverse variation',
        'x and y vary inversely when xy is constant: when one increases, the other decreases in the same ratio.',
        'x₁y₁ = x₂y₂. Example: 12 men finish a job in 15 days, so 20 men finish it in 12 × 15 / 20 = 9 days.'),
      n('Time and work',
        'If A finishes a job in n days, A’s work in one day is 1/n.',
        'A and B together do 1/a + 1/b of the work in a day, so they finish in ab/(a + b) days.',
        'Example: A takes 6 days and B takes 12 days; together they take 72/18 = 4 days.'),
    ] },
  'icse-algebraic-expressions': {
    summary: 'Terms, polynomials and their degree, and the four operations on algebraic expressions.',
    notes: [
      n('Terms and polynomials',
        'An expression is made of terms joined by + and − signs. In 5x²y, 5 is the numerical coefficient.',
        'Monomial: one term. Binomial: two terms. Trinomial: three terms.',
        'A polynomial has only whole-number powers of the variables. Its degree is the highest total power in any term: 3x²y + 5x has degree 3.'),
      n('Like and unlike terms',
        'Like terms have the same letters with the same powers: 3x²y and −7x²y.',
        'Only like terms can be added or subtracted; add or subtract their coefficients.'),
      n('Multiplication',
        'Multiply the coefficients and add the powers of the same letter: 3x² × 4x³ = 12x⁵.',
        'Multiply each term of one polynomial by each term of the other, then combine like terms.'),
      n('Division',
        'Divide the coefficients and subtract the powers: 12x⁵ ÷ 4x² = 3x³.',
        'To divide a polynomial by a monomial, divide every term. To divide by a binomial, use long division with the terms in descending powers.',
        'Dividend = divisor × quotient + remainder.'),
      n('Simplifying with brackets',
        'Remove brackets from the innermost outwards.',
        'A minus sign before a bracket changes the sign of every term inside it.'),
    ] },
  'icse-algebraic-identities': {
    summary: 'The standard identities for squares, products and cubes, and how to use them to expand and evaluate.',
    notes: [
      n('Identities',
        '(a + b)² = a² + 2ab + b²',
        '(a − b)² = a² − 2ab + b²',
        '(a + b)(a − b) = a² − b²',
        '(x + a)(x + b) = x² + (a + b)x + ab'),
      n('Useful results',
        'a² + b² = (a + b)² − 2ab = (a − b)² + 2ab.',
        '(a + b)² − (a − b)² = 4ab.',
        'If x + 1/x = k, then x² + 1/x² = k² − 2.'),
      n('Three terms and cubes',
        '(a + b + c)² = a² + b² + c² + 2ab + 2bc + 2ca.',
        '(a + b)³ = a³ + 3a²b + 3ab² + b³ and (a − b)³ = a³ − 3a²b + 3ab² − b³.'),
      n('Quick calculations',
        '102 × 98 = (100 + 2)(100 − 2) = 10000 − 4 = 9996.',
        '51² = (50 + 1)² = 2500 + 100 + 1 = 2601.'),
    ] },
  'icse-factorisation': {
    summary: 'Writing an expression as a product: common factors, grouping, difference of squares and trinomials.',
    notes: [
      n('Common factor', 'Take out the HCF of all the terms: 6x²y + 9xy² = 3xy(2x + 3y).'),
      n('Grouping', 'Group the terms so that each group has a common factor and the brackets match: ax + ay + bx + by = (a + b)(x + y).'),
      n('Difference of two squares', 'a² − b² = (a + b)(a − b). Example: 9x² − 25 = (3x + 5)(3x − 5).'),
      n('Trinomials',
        'Perfect square: a² ± 2ab + b² = (a ± b)².',
        'x² + px + q: find two numbers with sum p and product q. Example: x² + 7x + 12 = (x + 3)(x + 4).',
        'ax² + bx + c: split the middle term into two parts whose product is ac. Example: 2x² + 7x + 3 = 2x² + 6x + x + 3 = (2x + 1)(x + 3).'),
      n('Order of attack',
        'First take out any common factor, then look for one of the standard forms.',
        'Check by multiplying the factors back.'),
    ] },
  'icse-linear-equations-in-one-variable': {
    summary: 'Solving linear equations in one variable and using them for word problems.',
    notes: [
      n('Solving',
        'A linear equation has the variable to the power 1. Its solution is the value that makes both sides equal.',
        'The same number may be added to, subtracted from, multiplied into or divided into both sides.',
        'Transposing: a term moved to the other side changes its sign; a multiplier becomes a divisor.'),
      n('Equations with brackets and fractions',
        'Remove the brackets first. For fractions, multiply every term by the LCM of the denominators.',
        'For an equation of the form (ax + b)/(cx + d) = m/n, cross-multiply.',
        'Always check the answer in the original equation.'),
      n('Word problems',
        'Let the unknown be x, write the other quantities in terms of x, and form the equation from the condition given.',
        'Consecutive integers: x, x + 1, x + 2. Consecutive even or odd numbers: x, x + 2, x + 4.',
        'A two-digit number with tens digit x and units digit y is 10x + y.'),
    ] },
  'icse-linear-inequations': {
    summary: 'Solving linear inequations in one variable and showing the solution on a number line.',
    notes: [
      n('Signs and sets',
        '< less than, > greater than, ≤ less than or equal to, ≥ greater than or equal to.',
        'The replacement set is the set from which the variable takes its values (N, W, Z or R). The solution set contains the values that satisfy the inequation.'),
      n('Rules',
        'Adding or subtracting the same number on both sides keeps the sign.',
        'Multiplying or dividing by a positive number keeps the sign.',
        'Multiplying or dividing by a negative number reverses the sign: −2x < 6 gives x > −3.'),
      n('Number line',
        'For natural numbers or integers, mark the solutions with thick dots.',
        'For real numbers, draw a thick line; use a filled circle for a value that is included and a hollow circle for one that is not.'),
    ] },
  'icse-understanding-shapes': {
    summary: 'Polygons, their angle sums and regular polygons.',
    notes: [
      n('Polygons',
        'A polygon is a closed figure made of line segments. Convex: every interior angle is less than 180°. Concave: at least one interior angle is more than 180°.',
        'A polygon with n sides has n(n − 3)/2 diagonals.'),
      n('Angle sums',
        'Sum of the interior angles of a polygon with n sides = (n − 2) × 180° = (2n − 4) right angles.',
        'Sum of the exterior angles, one at each vertex, of any convex polygon = 360°.',
        'Interior angle + exterior angle at a vertex = 180°.'),
      n('Regular polygons',
        'All sides are equal and all angles are equal.',
        'Each exterior angle = 360° / n. Each interior angle = (n − 2) × 180° / n.',
        'Number of sides = 360° ÷ exterior angle. Example: an exterior angle of 40° gives 9 sides.'),
    ] },
  'icse-special-types-of-quadrilaterals': {
    summary: 'Parallelogram, rectangle, rhombus, square, trapezium and kite, with their properties.',
    notes: [
      n('Parallelogram',
        'Opposite sides are parallel and equal. Opposite angles are equal.',
        'Adjacent angles are supplementary (add up to 180°).',
        'The diagonals bisect each other, and each diagonal divides the parallelogram into two congruent triangles.'),
      n('Rectangle',
        'A parallelogram with every angle 90°.',
        'The diagonals are equal and bisect each other.'),
      n('Rhombus',
        'A parallelogram with all sides equal.',
        'The diagonals bisect each other at right angles and bisect the angles at the vertices.'),
      n('Square',
        'A rectangle with all sides equal.',
        'The diagonals are equal, bisect each other at right angles, and make 45° with the sides.'),
      n('Trapezium and kite',
        'Trapezium: one pair of opposite sides parallel. In an isosceles trapezium the non-parallel sides are equal, the base angles are equal and the diagonals are equal.',
        'Kite: two pairs of equal adjacent sides. The diagonals meet at right angles.'),
    ] },
  'icse-constructions': {
    summary: 'Constructing angles, bisectors and quadrilaterals with ruler and compasses.',
    notes: [
      n('Basic constructions',
        'Perpendicular bisector of a segment: draw arcs of the same radius (more than half the segment) from both ends, on both sides; join the two points where the arcs cross.',
        'Bisector of an angle: draw an arc from the vertex cutting both arms, then equal arcs from those two points; join the vertex to the point where they cross.',
        'Angles of 60°, 30°, 90°, 45° and 120° come from the 60° construction and bisection.'),
      n('Quadrilaterals',
        'A general quadrilateral needs five independent measurements, for example four sides and one diagonal, or three sides and the two included angles.',
        'A parallelogram needs three: two adjacent sides and the included angle, or two adjacent sides and a diagonal.',
        'A rhombus can be drawn from its two diagonals, which bisect each other at right angles. A square needs only one measurement.'),
      n('Method',
        'Draw a rough sketch first and mark the given measurements on it.',
        'Start with a triangle that can be drawn completely, then locate the fourth vertex.',
        'Leave all construction arcs visible.'),
    ] },
  'icse-representing-3-d-in-2-d': {
    summary: 'Polyhedra, Euler’s formula, nets and views of solids.',
    notes: [
      n('Polyhedra',
        'A polyhedron is a solid with flat polygonal faces. Faces meet in edges and edges meet in vertices.',
        'Prism: two identical parallel bases joined by rectangular faces. Pyramid: one base, and triangular faces meeting at a point.',
        'Cylinders, cones and spheres have curved surfaces and are not polyhedra.'),
      n('Euler’s formula',
        'For any polyhedron, F + V − E = 2.',
        'Cube: F = 6, V = 8, E = 12. Triangular prism: F = 5, V = 6, E = 9. Square pyramid: F = 5, V = 5, E = 8.'),
      n('Nets and views',
        'A net is a flat pattern that folds into the solid.',
        'A solid is described by its front, side and top views.',
        'An oblique sketch shows the front face in true shape; an isometric sketch on dot paper keeps the measurements along three directions.'),
    ] },
  'icse-area-of-a-trapezium-and-a-polygon': {
    summary: 'Areas of triangles, quadrilaterals and polygons.',
    notes: [
      n('Triangle',
        'Area = ½ × base × height.',
        'With sides a, b and c: area = √[s(s − a)(s − b)(s − c)], where s = (a + b + c)/2.',
        'Equilateral triangle of side a: area = (√3/4)a².'),
      n('Quadrilaterals',
        'Rectangle: l × b. Square: side². Parallelogram: base × height.',
        'Rhombus: ½ × product of the diagonals.',
        'Trapezium: ½ × (sum of the parallel sides) × distance between them.',
        'Any quadrilateral: ½ × diagonal × (sum of the perpendiculars on it from the other two vertices).'),
      n('Polygon',
        'Divide the polygon into triangles and trapeziums, find each area and add.',
        'Keep all lengths in the same unit; the area is in square units.'),
    ] },
  'icse-surface-area-volume-and-capacity': {
    summary: 'Surface area and volume of cuboids, cubes and cylinders, and units of capacity.',
    notes: [
      n('Cuboid and cube',
        'Cuboid: volume = l × b × h, total surface area = 2(lb + bh + hl), area of the four walls = 2(l + b)h.',
        'Cube of side a: volume = a³, total surface area = 6a², diagonal = a√3.',
        'Diagonal of a cuboid = √(l² + b² + h²).'),
      n('Cylinder',
        'Curved surface area = 2πrh. Total surface area = 2πr(r + h). Volume = πr²h.',
        'Hollow cylinder with outer radius R and inner radius r: volume of material = π(R² − r²)h.'),
      n('Capacity',
        '1 litre = 1000 cm³. 1 m³ = 1000 litres = 1 kilolitre. 1 ml = 1 cm³.',
        'Keep all dimensions in the same unit before calculating.'),
    ] },
  'icse-data-handling': {
    summary: 'Organising data in frequency tables and showing it with bar graphs, histograms and pie charts.',
    notes: [
      n('Frequency distribution',
        'Raw data is grouped into class intervals; the number of values in a class is its frequency.',
        'In the class 10–20, 10 is the lower limit and 20 is the upper limit. Class size = upper limit − lower limit. Class mark = (lower limit + upper limit)/2.',
        'In the exclusive form (10–20, 20–30) a value equal to the upper limit is counted in the next class.'),
      n('Graphs',
        'Bar graph: bars of equal width with gaps, with heights proportional to the values.',
        'Histogram: for grouped data with continuous classes; the bars touch each other.',
        'Pie chart: central angle of a sector = (value / total) × 360°.'),
    ] },
  'icse-probability': {
    summary: 'Experiments, outcomes and events, and the probability of an event.',
    notes: [
      n('Basic terms',
        'An experiment whose result is uncertain is a random experiment. Each possible result is an outcome; the set of all outcomes is the sample space.',
        'An event is a collection of outcomes.'),
      n('Probability',
        'P(E) = number of favourable outcomes / total number of equally likely outcomes.',
        '0 ≤ P(E) ≤ 1. An impossible event has probability 0 and a sure event has probability 1.',
        'P(not E) = 1 − P(E).'),
      n('Common sample spaces',
        'A coin: 2 outcomes. Two coins: 4 outcomes (HH, HT, TH, TT). A die: 6 outcomes.',
        'A pack of cards: 52 cards in 4 suits of 13; 26 red and 26 black; 12 face cards.'),
    ] },
};
