// Blog articles and exam news, newest first. To add one, copy an entry and change it.
// category: 'Blog' or 'Exam News'. date: 'YYYY-MM-DD'. body: paragraphs; an entry { h: '...' } is a heading and { list: [...] } a bullet list.
// For exam news, always give the official notice in `source` so readers can check it.
export const POSTS = [
  {
    slug: 'class-10-maths-formulas-chapter-wise-list', category: 'Blog', date: '2026-10-05',
    title: 'Class 10 Maths formulas: the complete chapter-wise list',
    summary: 'Every important Class 10 Maths formula in one place, chapter by chapter, for CBSE and ICSE revision.',
    body: [
      "Formulas are the quickest marks in Maths, but only if you can recall them without looking. Here is the list for the whole Class 10 course, in chapter order. Each chapter also has its own one-page [formula bank](/self-study) you can download and print.",
      { h: 'Algebra' },
      { list: [
        "Real Numbers: HCF × LCM = product of the two numbers. Every composite number has one and only one prime factorisation.",
        "Polynomials: sum of zeroes = −b/a and product of zeroes = c/a, for ax² + bx + c.",
        "Pair of linear equations: if a₁/a₂ ≠ b₁/b₂ there is one solution; if a₁/a₂ = b₁/b₂ ≠ c₁/c₂ there is none; if all three ratios are equal there are infinitely many.",
        "Quadratic equations: discriminant D = b² − 4ac. For D > 0 the roots are real and different, for D = 0 they are real and equal, for D < 0 there are no real roots. Roots: x = (−b ± √D) / 2a.",
        "Arithmetic progression: nth term = a + (n − 1)d. Sum of n terms = n/2 [2a + (n − 1)d] = n/2 (a + l).",
      ] },
      { h: 'Geometry and coordinate geometry' },
      { list: [
        "Triangles: if DE ∥ BC then AD/DB = AE/EC. For similar triangles, the ratio of areas is the square of the ratio of corresponding sides.",
        "Circles: the tangent is perpendicular to the radius at the point of contact, and the two tangents from an outside point are equal in length.",
        "Distance between (x₁, y₁) and (x₂, y₂) = √[(x₂ − x₁)² + (y₂ − y₁)²].",
        "Section formula (internal, ratio m : n) = ((mx₂ + nx₁)/(m + n), (my₂ + ny₁)/(m + n)). Mid-point is the case m = n.",
      ] },
      { h: 'Trigonometry' },
      { list: [
        "sin θ = opposite/hypotenuse, cos θ = adjacent/hypotenuse, tan θ = opposite/adjacent.",
        "sin²θ + cos²θ = 1, 1 + tan²θ = sec²θ, 1 + cot²θ = cosec²θ.",
        "Heights and distances: tan of the angle of elevation = height/horizontal distance.",
      ] },
      { h: 'Mensuration' },
      { list: [
        "Circle: circumference 2πr, area πr². Sector: area = (θ/360) × πr², arc length = (θ/360) × 2πr.",
        "Cylinder: curved surface 2πrh, total surface 2πr(r + h), volume πr²h.",
        "Cone: slant height l = √(r² + h²), curved surface πrl, volume ⅓πr²h.",
        "Sphere: surface 4πr², volume ⁴⁄₃πr³. Hemisphere: curved surface 2πr², total surface 3πr², volume ⅔πr³.",
      ] },
      { h: 'Statistics and probability' },
      { list: [
        "Mean = Σfx / Σf. Median = l + [(n/2 − cf) / f] × h. Mode = l + [(f₁ − f₀) / (2f₁ − f₀ − f₂)] × h.",
        "Empirical relation: mode = 3 × median − 2 × mean.",
        "Probability of an event = favourable outcomes / total outcomes. P(E) + P(not E) = 1, and a probability is always between 0 and 1.",
      ] },
      { h: 'Extra for ICSE students' },
      { list: [
        "Remainder theorem: the remainder when f(x) is divided by (x − a) is f(a).",
        "Slope of a line = (y₂ − y₁)/(x₂ − x₁). Equation of a line: y = mx + c.",
        "Compound interest: A = P (1 + r/100)ⁿ. Recurring deposit interest = P × n(n + 1)/24 × r/100, where n is the number of months.",
      ] },
      { h: 'How to learn them' },
      "Do not try to memorise the whole list in one evening. Learn one chapter's formulas, then write them from memory the next day. The [chapter notes](/class-10) show where each formula comes from, which makes it much easier to remember.",
    ],
  },
  {
    slug: 'how-to-score-full-marks-in-class-10-maths-30-day-plan', category: 'Blog', date: '2026-10-05',
    title: 'How to score full marks in Class 10 Maths: a 30-day plan',
    summary: 'A realistic month-long plan to revise the whole Class 10 Maths course and practise for the board paper.',
    body: [
      "Maths is the most scoring subject in Class 10, because every correct step earns marks. This plan assumes you have studied the whole syllabus once and now want to revise and practise. It takes about two hours a day.",
      { h: 'Know the paper first' },
      "The CBSE Standard Maths theory paper is for 80 marks and has five sections: A (20 one-mark questions), B (5 questions of 2 marks), C (6 questions of 3 marks), D (4 questions of 5 marks) and E (3 case-study questions of 4 marks). Boards revise the pattern from time to time, so confirm it on the official CBSE website before you start.",
      { h: 'Days 1 to 18: one chapter at a time' },
      { list: [
        "Spend one day on each of the 14 chapters, in this order of difficulty: Real Numbers, Polynomials, Pair of Linear Equations, Quadratic Equations, Arithmetic Progressions, Coordinate Geometry, Triangles, Circles, Introduction to Trigonometry, Applications of Trigonometry, Areas Related to Circles, Surface Areas and Volumes, Statistics, Probability.",
        "For each chapter: read the [short notes](/class-10), learn the formula bank, solve the DPP sheet and take the chapter [test](/tests).",
        "Use the remaining four days to redo the chapters in which your test score was below 7 out of 10.",
      ] },
      { h: 'Days 19 to 26: previous year questions' },
      "Solve the previous year questions chapter-wise, writing full answers and timing yourself. Compare each solution with the given one, step by step. Our post on [using previous year questions](/blog/how-to-use-previous-year-questions) explains how.",
      { h: 'Days 27 to 30: full papers' },
      "Attempt one full paper on each of these days under exam conditions: three hours, no breaks, no phone. Use the [MathSetu sample paper](/sample-papers) first, then check your answers with the solutions PDF. After each paper, list the marks you lost and the reason: concept, calculation or presentation.",
      { h: 'Habits that add marks' },
      { list: [
        "Write every step, because board marking is step-wise.",
        "Write units and a closing sentence in word problems.",
        "Check signs and arithmetic in the last two minutes of each answer.",
        "Sleep properly in the last week. A tired mind makes silly mistakes.",
      ] },
      "If you get stuck on a question during the month, send it through [Ask a Doubt](/doubts) instead of leaving it for later.",
    ],
  },
  {
    slug: 'how-to-overcome-fear-of-maths', category: 'Blog', date: '2026-10-05',
    title: 'How to overcome fear of Maths: a practical guide for students',
    summary: 'Maths fear usually comes from one missed idea, not from lack of ability. Here is how to find it and fix it.',
    body: [
      "If you feel nervous the moment a Maths paper is placed in front of you, you are not alone. Fear of Maths is very common, and it is rarely about ability. It usually starts with one idea that was never fully understood, after which every new chapter feels harder than the last.",
      { h: 'Why Maths feels frightening' },
      { list: [
        "Maths builds on itself. If fractions or negative numbers were shaky in Class 7, algebra in Class 8 and 9 feels confusing, and the confusion grows.",
        "Exams reward speed and accuracy together, so one wrong answer feels like proof that you are bad at it.",
        "Many students are afraid to ask a doubt in class, so a small gap stays open for years.",
      ] },
      { h: 'Step 1: find the missed idea' },
      "Pick the chapter that scares you most and ask: which question was the first one I could not do? Go back to the chapter before it. The weak point is often one or two chapters earlier than where you got stuck.",
      { h: 'Step 2: go slow, with easy questions first' },
      "Read the [short notes](/self-study) of that earlier chapter and solve only the easiest questions. Success on easy questions rebuilds confidence, and confidence matters in Maths more than in most subjects.",
      { h: 'Step 3: practise a little every day' },
      "Fifteen to twenty minutes a day beats a three-hour session once a week. A daily practice sheet keeps the ideas fresh and shows your progress.",
      { h: 'Step 4: test yourself without pressure' },
      "A short chapter [test](/tests) shows exactly what you know. Treat a low score as information, not as a verdict. Read the explanations and take it again a few days later.",
      { h: 'Step 5: ask your doubt the same day' },
      "A doubt that is cleared today does not become a gap next year. If you are shy to ask in class, use [Ask a Doubt](/doubts), where you can send a question with a photo and get a step-by-step answer in private.",
      { h: 'A note for parents' },
      "Please avoid saying that Maths is difficult or that you were also weak at it. Children pick up that attitude quickly. Praise effort and steady practice rather than marks.",
      "The aim is not to be fast; it is to understand each step once, properly. Speed comes later, from practice.",
    ],
  },
  {
    slug: 'trigonometry-values-table-how-to-remember', category: 'Blog', date: '2026-10-05',
    title: 'Trigonometry values table: an easy way to remember it',
    summary: 'A simple pattern for the sin, cos and tan values of 0°, 30°, 45°, 60° and 90°, with practice tips.',
    body: [
      "The trigonometric values of 0°, 30°, 45°, 60° and 90° are used in almost every question of Introduction to Trigonometry and Heights and Distances. You do not need to cram them: there is a pattern.",
      { h: 'The sine pattern' },
      "Write the numbers 0, 1, 2, 3, 4 under the angles 0°, 30°, 45°, 60°, 90°. Take the square root of each, then divide by 2. That gives sin 0° = 0, sin 30° = 1/2, sin 45° = 1/√2, sin 60° = √3/2 and sin 90° = 1.",
      { h: 'The cosine pattern' },
      "Cosine is the sine list written backwards: cos 0° = 1, cos 30° = √3/2, cos 45° = 1/√2, cos 60° = 1/2 and cos 90° = 0. This works because cos θ = sin (90° − θ).",
      { h: 'The tangent' },
      "Do not learn tan separately. Use tan θ = sin θ / cos θ. For example, tan 30° = (1/2) ÷ (√3/2) = 1/√3, tan 45° = 1, and tan 60° = √3. Tan 90° is not defined, because cos 90° is zero.",
      { h: 'The full table' },
      { list: [
        "0°: sin 0, cos 1, tan 0",
        "30°: sin 1/2, cos √3/2, tan 1/√3",
        "45°: sin 1/√2, cos 1/√2, tan 1",
        "60°: sin √3/2, cos 1/2, tan √3",
        "90°: sin 1, cos 0, tan not defined",
      ] },
      { h: 'Check yourself with the identity' },
      "Whenever you are unsure, test with sin²θ + cos²θ = 1. For 30°: (1/2)² + (√3/2)² = 1/4 + 3/4 = 1, so the pair is right.",
      { h: 'How to practise' },
      "Cover the table and rebuild it from the pattern every day for a week. Then solve a few expressions such as sin 60° cos 30° + sin 30° cos 60°, which equals 1. The [Introduction to Trigonometry chapter](/class-10/trigonometry) has solved examples, a formula bank and a chapter test, and the [Applications of Trigonometry chapter](/class-10/applications-of-trigonometry) uses these values to find heights and distances.",
    ],
  },
  {
    slug: 'icse-class-10-maths-paper-pattern-and-preparation', category: 'Blog', date: '2026-10-05',
    title: 'ICSE Class 10 Maths: paper pattern and how to prepare',
    summary: 'How the ICSE Class 10 Maths paper is laid out, which topics need special practice, and a simple preparation plan.',
    body: [
      "The ICSE (CISCE) Class 10 Maths paper is for 80 marks and is written in two and a half hours, with 20 marks given for internal assessment. It has two sections. Section A is compulsory and carries 40 marks. In Section B you attempt any four of the seven questions, each for 10 marks. Always confirm the current pattern in the CISCE syllabus, since it can change.",
      { h: 'Section A: no choice, so no weak chapter' },
      "Because Section A covers the whole syllabus and has no choice, you cannot skip a topic. Short questions on GST, banking, shares, factor theorem, matrices, ratio and proportion, and mensuration are very common, and they are quick marks if the method is clear.",
      { h: 'Section B: use the choice wisely' },
      "In Section B, read all seven questions first, then pick the four you are most sure of. Spend the first five minutes on this, not on the first question you see.",
      { h: 'Topics that need regular practice' },
      { list: [
        "Commercial mathematics: GST, banking and shares. These need fixed formulas and careful reading of the question.",
        "Quadratic equations and their word problems.",
        "Coordinate geometry: section formula, equation of a line and slope.",
        "Matrices: order, multiplication and finding unknowns.",
        "Constructions and loci. Practise with a compass and ruler, not only by reading.",
        "Statistics: mean by the step-deviation method, median, quartiles and ogives.",
      ] },
      { h: 'A simple plan' },
      { list: [
        "Revise one chapter at a time from the [ICSE chapter notes](/class-10), then take its chapter [test](/tests).",
        "Solve the exercise questions of your Selina or school book yourself before checking the answers.",
        "Practise a full paper in two and a half hours. The [MathSetu ICSE sample paper](/sample-papers) follows this pattern and includes worked solutions.",
      ] },
      "Write every step of your working, because ICSE marks are given for method as well as for the answer. If you are also comparing the two boards, read [how CBSE and ICSE Class 10 Maths differ](/blog/cbse-and-icse-class-10-maths-compared).",
    ],
  },
  {
    slug: 'how-to-use-ncert-solutions-the-right-way', category: 'Blog', date: '2026-10-05',
    title: 'How to use NCERT solutions the right way',
    summary: 'NCERT solutions help only if you try the question first. Here is how to use them without losing marks later.',
    body: [
      "Many students open the solution as soon as a question looks hard. It feels like progress, but it often leads to marks lost later, because reading a solution and producing one are different skills. Used properly, NCERT solutions are one of the best study tools for CBSE Maths.",
      { h: 'Try first, even if you fail' },
      "Give each question a fair attempt of five to ten minutes. Even a wrong attempt helps, because when you then read the solution you notice exactly where your thinking differed.",
      { h: 'Read the solution one line at a time' },
      "Cover the page and uncover one line at a time. After each line, ask: could I have written this? If not, work out why that step is allowed.",
      { h: 'Redo the question without the book' },
      "Close the solution and solve the question again from scratch. If you can do it, mark it done. If not, repeat the next day. A question solved twice without help is learned.",
      { h: 'Match your answer to the board style' },
      "Notice how the solution is written: the given data, the formula, the substitution, the answer with units. Board examiners expect this layout, so copy the style, not the words.",
      { h: 'Do not stop at the textbook' },
      "Exercise questions show the basic types. For the board exam you also need harder and mixed questions, so move on to the [DPP sheets](/self-study), the chapter [tests](/tests) and the previous year questions.",
      { h: 'Where to find them' },
      "MathSetu has step-by-step NCERT solutions for the CBSE chapters, written in our own words with the figures redrawn. Open any [Class 10 chapter](/class-10) and look for the NCERT Solutions tab. They are added chapter by chapter, and the questions are numbered as in the textbook so you can follow along.",
      "If a solution still does not make sense, send the exact step to [Ask a Doubt](/doubts) and we will explain it.",
    ],
  },
  {
    slug: 'case-study-and-assertion-reason-questions-class-10-maths', category: 'Blog', date: '2026-10-05',
    title: 'Case study and assertion-reason questions in Class 10 Maths',
    summary: 'How to read and solve case-study and assertion-reason questions in the CBSE Maths paper.',
    body: [
      "Two question types in the CBSE Class 10 Maths paper worry students more than they should: the case-study questions in Section E and the assertion-reason questions in Section A. Both are easy once you know how to read them.",
      { h: 'Case-study questions' },
      "A case study gives a real-life situation, such as a staircase, a garden or a table of data, followed by three short parts. They are usually worth 4 marks in total, and the parts get harder as you go on. Every part uses a chapter you already know.",
      { list: [
        "Read the passage twice and underline the numbers.",
        "Draw a quick figure or write the data as a small table before you start.",
        "Identify the chapter: the words sum, term and difference suggest an AP; angle of elevation suggests trigonometry; coordinates suggest the distance or section formula.",
        "Answer part by part, writing the formula and the working, as in any other question.",
        "If a part has an internal choice (OR), choose the one you are more sure of and do not attempt both.",
      ] },
      { h: 'Assertion-reason questions' },
      "You are given two statements: an Assertion (A) and a Reason (R). The four options are always the same: both true and R explains A; both true but R does not explain A; A true and R false; A false and R true.",
      { list: [
        "First decide whether A is true. Check it with a small example if needed.",
        "Then decide whether R is true, independently of A.",
        "If both are true, ask: does R actually explain why A is true? A true statement placed next to another true statement is not always its reason.",
        "Do not choose by feeling. Decide each statement, and the option follows.",
      ] },
      { h: 'A worked example' },
      "Assertion: when a die is thrown once, the probability of getting a prime number is 1/2. Reason: the prime numbers on a die are 2, 3 and 5. There are 3 primes among 6 equally likely outcomes, so A is true. R is true as well, and it is exactly the count used in A. So both are true and R explains A.",
      { h: 'Practise' },
      "Practise both types with the full-length [MathSetu sample paper](/sample-papers), which includes assertion-reason and case-study questions with solutions.",
    ],
  },
  {
    slug: 'last-7-days-revision-plan-class-10-maths', category: 'Blog', date: '2026-10-05',
    title: 'Last 7 days before the Maths exam: a revision plan',
    summary: 'What to revise, what to skip and how to stay calm in the final week before the Class 10 Maths board paper.',
    body: [
      "The last week is not the time to start new topics. It is the time to fix weak spots, practise full papers and arrive at the exam calm. Here is a plan that works for CBSE and ICSE.",
      { h: 'Day 1: list your weak topics' },
      "Look at the scores of your chapter tests and your last sample paper. Write the three chapters where you lose the most marks. These get the most time this week.",
      { h: 'Days 2 and 3: weak chapters' },
      "Revise the notes of the weak chapters, then solve the DPP and previous year questions of only those chapters. Do not read new theory.",
      { h: 'Day 4: formulas and standard results' },
      "Write all formulas from memory on a blank page, chapter by chapter, and check them with the [formula list](/blog/class-10-maths-formulas-chapter-wise-list). Repeat the ones you missed. Also revise the trigonometric values table and the standard identities.",
      { h: 'Days 5 and 6: two full papers' },
      "Attempt one full paper on each day, in the exam time, at the exam hour if possible. Use the [sample papers](/sample-papers) and check them with the solutions. Mark the sections where you lose time.",
      { h: 'Day 7: light revision and rest' },
      "Go through your list of mistakes, read the formulas once, and stop early. Prepare your geometry box, pens and admit card, then go to bed on time.",
      { h: 'In the exam hall' },
      { list: [
        "Begin by reading through the whole paper and marking the questions you are sure of.",
        "Start with the questions you can do. Confidence early helps the rest of the paper.",
        "Write every step, keep your working neat, and give units and a closing line.",
        "Keep ten minutes at the end to check signs, calculations and that you answered what was asked.",
      ] },
      "Finally, do not compare answers with friends outside the hall. It cannot change your marks and it can spoil the next paper. Stay focused on the next day's subject, and trust the practice you have done.",
    ],
  },
  {
    slug: 'how-to-study-a-maths-chapter', category: 'Blog', date: '2026-10-04',
    title: 'How to study a Maths chapter in four steps',
    summary: 'A simple routine for every chapter: notes, formulas, practice, then a test.',
    body: [
      'Most students read a chapter once, feel that they have understood it, and move on. The marks are lost later, when the same chapter has to be recalled in an exam. A fixed routine for every chapter prevents this.',
      { h: '1. Read the short notes with a pen in hand' },
      'Do not only read the solved examples. Cover the solution, try the example yourself, and then compare. An example you solved yourself stays with you much longer than one you read.',
      { h: '2. Learn the formula bank' },
      'Write the formulas of the chapter from memory on a blank page, then check them against the formula bank. Repeat the next day for the ones you missed. Five minutes a day is enough.',
      { h: '3. Solve the DPP without looking' },
      'Attempt every question of the DPP sheet before opening the answer key. Mark the questions you got wrong and do only those again after two days.',
      { h: '4. Take the chapter test' },
      'A timed test shows whether you can do the chapter under exam pressure. If you score below 7 out of 10, read the explanations, go back to the notes for those topics and take the test again.',
      { h: 'How long should this take?' },
      'For most chapters, two to three sittings of 45 minutes each. Short, regular sittings work better than one long one.',
    ],
  },
  {
    slug: 'why-you-lose-marks-in-maths', category: 'Blog', date: '2026-10-04',
    title: 'Why you lose marks in Maths even when you know the method',
    summary: 'Seven common slips that cost marks in school and board exams, and how to stop making them.',
    body: [
      'Many marks are lost not because the method is unknown, but because of small slips. These are the ones seen most often.',
      { list: [
        'Sign errors: forgetting to change the sign when a term crosses the equals sign, or when a bracket has a minus in front of it.',
        'Skipping steps: board examiners give marks for steps. A correct final answer with no working can lose marks, and a wrong answer with correct steps still earns some.',
        'Units: writing an area in cm instead of sq cm, or leaving the unit out altogether.',
        'Not answering what was asked: finding x when the question asked for 2x + 1, or the radius when it asked for the diameter.',
        'Copying the question wrongly: one wrong digit at the start makes the whole solution wrong.',
        'Rounding too early: keep fractions or surds until the last step, then round once.',
        'No final statement: in word problems, end with a sentence that answers the question.',
      ] },
      { h: 'A two-minute check' },
      'Before handing in the paper, go through each answer and ask three things: did I answer what was asked, are the units there, and does the answer look reasonable? A person\'s age cannot be negative and a probability cannot be more than 1.',
    ],
  },
  {
    slug: 'how-to-use-previous-year-questions', category: 'Blog', date: '2026-10-04',
    title: 'How to use previous year questions properly',
    summary: 'Previous year questions are most useful after the chapter is done, not before.',
    body: [
      'Previous year questions (PYQs) show how a chapter is actually asked in the board exam: which topics come again and again, and how many marks they carry. They are a tool for the last stage of preparation, not the first.',
      { h: 'When to start' },
      'Start the PYQs of a chapter only after you have finished its notes and DPP. If you start earlier, you end up reading solutions instead of solving.',
      { h: 'How to solve them' },
      { list: [
        'Solve topic-wise first, so that you see every type of question from one topic together.',
        'Write full solutions, as you would in the exam, and time yourself: about one and a half minutes per mark.',
        'Check your solution against the given one step by step, not just the final answer.',
        'Keep a list of the questions you could not do. Redo that list a week later.',
      ] },
      { h: 'What PYQs cannot do' },
      'They do not replace the textbook. Boards also ask new questions every year, so a student who only memorises old questions is caught out. Use PYQs to practise, and the textbook and notes to understand.',
    ],
  },
  {
    slug: 'cbse-and-icse-class-10-maths-compared', category: 'Blog', date: '2026-10-04',
    title: 'CBSE and ICSE Class 10 Maths: how the two differ',
    summary: 'The two boards share most of the syllabus, but each has topics the other does not.',
    body: [
      'Students who change boards, or who use material written for the other board, often ask how different the two Class 10 Maths courses are. Most of the algebra, geometry, trigonometry, mensuration, statistics and probability is common. The differences are mainly these.',
      { h: 'Topics found only in ICSE' },
      { list: ['Commercial mathematics: GST, banking (recurring deposits), shares and dividend', 'Linear inequations', 'Ratio and proportion, remainder and factor theorems', 'Matrices', 'Geometric progression', 'Reflection and equation of a line', 'Loci'] },
      { h: 'Topics found only in CBSE' },
      { list: ['Real numbers (the Fundamental Theorem of Arithmetic and irrational numbers)', 'Pair of linear equations in two variables as a separate chapter', 'Areas related to circles (sectors and segments)'] },
      { h: 'What this means for you' },
      'On MathSetu, CBSE and ICSE chapters are kept separate, so open the chapter list of your own board. If a chapter has the same name in both boards, the notes may still differ in depth, so use the one for your board.',
      'Syllabuses are revised from time to time. Always check the current syllabus on the official website of your board.',
    ],
  },
];

// Official websites for dates, syllabus and notices. Exam news on this site always links to one of these.
export const OFFICIAL = [
  { name: 'CBSE', url: 'https://www.cbse.gov.in', about: 'Date sheets, circulars and results' },
  { name: 'CBSE Academic', url: 'https://cbseacademic.nic.in', about: 'Syllabus and official sample papers' },
  { name: 'CISCE', url: 'https://cisce.org', about: 'ICSE syllabus, timetable and specimen papers' },
  { name: 'NCERT', url: 'https://ncert.nic.in', about: 'Textbooks' },
  { name: 'SOF', url: 'https://sofworld.org', about: 'IMO dates, syllabus and results' },
];
