// One-line summary of each chapter, shown under the chapter title. Keyed by class, then chapter slug.
export default {
  'class-8': {
    'a-square-and-a-cube': 'Square numbers, cube numbers and their roots, with the patterns that help you spot and find them.',
    'power-play': 'Exponents and their laws, powers of 10, scientific notation and how quickly exponential growth builds up.',
    'a-story-of-numbers': 'How people counted and wrote numbers through history, and why the place value system with zero is so powerful.',
    'quadrilaterals': 'Types of quadrilaterals and the properties of their sides, angles and diagonals.',
    'number-play': 'Patterns in numbers: odd and even (parity), sums of consecutive numbers and divisibility rules, used to solve number puzzles.',
    'we-distribute-yet-things-multiply': 'The distributive property, multiplying algebraic expressions and the three standard identities, with their use in quick calculation.',
    'proportional-reasoning-1': 'Ratios, proportion and the unit method, used to compare quantities and to scale them up or down.',
    'fractions-in-disguise': 'Percentages as fractions with denominator 100: converting, finding a percentage of a quantity, and percentage change.',
    'baudhayana-pythagoras-theorem': 'The relation between the sides of a right-angled triangle, its converse, and how to use it to find lengths.',
    'proportional-reasoning-2': 'Ratios with more than two terms, scales on maps, and direct and inverse proportion.',
    'exploring-some-geometric-themes': 'Fractals built by repeating a rule, and ways of seeing and drawing three-dimensional solids.',
    'tales-by-dots-and-lines': 'Describing data with a single value using the mean and the median, and reading data from tables and plots.',
    'algebra-play': 'Using algebra to explain number tricks, patterns and puzzles.',
    'area': 'Area formulas for triangles and quadrilaterals, and how to find the area of any polygon by splitting it up.',
    'icse-rational-numbers': 'Rational numbers, their properties under the four operations, and how to place them on a number line.',
    'icse-exponents-powers': 'Positive, zero and negative exponents and the laws for working with them.',
    'icse-squares-and-square-roots': 'Perfect squares, their properties, and finding square roots by prime factorisation and by division.',
    'icse-cubes-and-cube-roots': 'Perfect cubes and finding cube roots by prime factorisation.',
    'icse-playing-with-numbers': 'Numbers in general form, digit puzzles and tests of divisibility.',
    'icse-sets': 'Sets, the ways of writing them, types of sets, and union, intersection and Venn diagrams.',
    'icse-percent-and-percentage': 'Percentages, converting between fractions, decimals and percentages, and percentage increase and decrease.',
    'icse-profit-loss-and-discount': 'Cost price, selling price, profit and loss per cent, marked price and discount.',
    'icse-simple-and-compound-interest': 'Simple interest and compound interest, and how they differ.',
    'icse-direct-and-inverse-variations': 'Direct and inverse variation, the unitary method, and time and work.',
    'icse-algebraic-expressions': 'Terms, polynomials and their degree, and the four operations on algebraic expressions.',
    'icse-algebraic-identities': 'The standard identities for squares, products and cubes, and how to use them to expand and evaluate.',
    'icse-factorisation': 'Writing an expression as a product: common factors, grouping, difference of squares and trinomials.',
    'icse-linear-equations-in-one-variable': 'Solving linear equations in one variable and using them for word problems.',
    'icse-linear-inequations': 'Solving linear inequations in one variable and showing the solution on a number line.',
    'icse-understanding-shapes': 'Polygons, their angle sums and regular polygons.',
    'icse-special-types-of-quadrilaterals': 'Parallelogram, rectangle, rhombus, square, trapezium and kite, with their properties.',
    'icse-constructions': 'Constructing angles, bisectors and quadrilaterals with ruler and compasses.',
    'icse-representing-3-d-in-2-d': 'Polyhedra, Euler’s formula, nets and views of solids.',
    'icse-area-of-a-trapezium-and-a-polygon': 'Areas of triangles, quadrilaterals and polygons.',
    'icse-surface-area-volume-and-capacity': 'Surface area and volume of cuboids, cubes and cylinders, and units of capacity.',
    'icse-data-handling': 'Organising data in frequency tables and showing it with bar graphs, histograms and pie charts.',
    'icse-probability': 'Experiments, outcomes and events, and the probability of an event.',
  },
  'class-9': {
    'orienting-yourself-coordinates': 'The Cartesian plane: axes, coordinates, quadrants and the distance between two points.',
    'linear-polynomials': 'Linear patterns and relationships, linear polynomials, their zeroes and their straight-line graphs.',
    'the-world-of-numbers': 'From natural numbers to real numbers: rational and irrational numbers, their decimal forms and the number line.',
    'algebraic-identities': 'Algebraic identities seen as areas, and their use in expanding, factorising and simplifying.',
    'up-and-down-round-and-round': 'Circles: chords, arcs, the angles they subtend and cyclic quadrilaterals.',
    'perimeter-and-area': 'Perimeter and area of triangles, rectangles and circles, including Heron’s formula, arcs and sectors.',
    'introduction-to-probability': 'Randomness, sample spaces, and experimental and theoretical probability.',
    'sequences-and-progressions': 'Sequences given by explicit and recursive rules, and arithmetic and geometric progressions with their sums.',
    'propositions-and-converses': 'Mathematical statements, their converses, counterexamples and what it takes to prove a statement.',
    'understanding-data': 'Combining data from groups of different sizes: weighted averages, mixtures, percentages and stacked bar charts.',
    'the-world-of-algorithms': 'Algorithms as step-by-step procedures: finding divisors, GCD, LCM and primes, and making procedures efficient.',
    'quadrilaterals': 'Properties of parallelograms, conditions for a quadrilateral to be a parallelogram, and the mid-point theorem.',
    'two-variables-one-line': 'Linear equations in two variables, their solutions and their straight-line graphs.',
    'surface-area-and-volume': 'Surface areas and volumes of cuboids, cylinders, cones and spheres.',
    'icse-rational-and-irrational-numbers': 'Rational and irrational numbers, surds and rationalising the denominator.',
    'icse-compound-interest-without-using-formula': 'Finding compound interest year by year, where each year’s amount becomes the next year’s principal.',
    'icse-compound-interest-using-formula': 'The compound interest formula and its use for different rates, half-yearly compounding, growth and depreciation.',
    'icse-expansions': 'Expanding squares and cubes of binomials and trinomials, and the results that follow from them.',
    'icse-factorisation': 'Factorising by common factors, grouping, splitting the middle term, and the square and cube identities.',
    'icse-simultaneous-linear-equations': 'Solving a pair of linear equations by substitution, elimination and cross-multiplication, with word problems.',
    'icse-indices-exponents': 'Laws of indices, including negative and fractional indices, and solving exponential equations.',
    'icse-logarithms': 'Logarithms as the reverse of indices, and the laws used to simplify and solve with them.',
    'icse-triangles-congruency-in-triangles': 'Congruent triangles and the conditions that prove congruence.',
    'icse-isosceles-triangles': 'Properties of isosceles and equilateral triangles.',
    'icse-inequalities': 'Relations between unequal sides and angles of a triangle.',
    'icse-mid-point-and-its-converse': 'The mid-point theorem, its converse and the intercept theorem.',
    'icse-pythagoras-theorem': 'Pythagoras theorem, its converse and applications.',
    'icse-rectilinear-figures': 'Polygons and their angle sums, and the properties of parallelograms, rectangles, rhombuses, squares and trapeziums.',
    'icse-construction-of-polygons': 'Constructing quadrilaterals and regular polygons with ruler and compasses.',
    'icse-area-theorems': 'Area relations between parallelograms and triangles on the same base and between the same parallels.',
    'icse-circle': 'Chord properties of a circle and the relation between equal chords and arcs.',
    'icse-statistics': 'Collecting and tabulating data, frequency distributions, and drawing histograms and frequency polygons.',
    'icse-mean-and-median': 'Mean and median of ungrouped data and the properties of the mean.',
    'icse-area-and-perimeter-of-plane-figures': 'Perimeter and area of triangles, quadrilaterals and circles.',
    'icse-solids': 'Surface area and volume of cuboids and cubes, cross-sections and the flow of water.',
    'icse-trigonometrical-ratios': 'The six trigonometrical ratios of an acute angle and the relations between them.',
    'icse-trigonometrical-ratios-of-standard-angles': 'Values of the trigonometrical ratios for 0°, 30°, 45°, 60° and 90°, and their use.',
    'icse-solution-of-right-triangles': 'Finding unknown sides and angles of right-angled triangles using trigonometrical ratios.',
    'icse-complementary-angles': 'Trigonometrical ratios of complementary angles.',
    'icse-co-ordinate-geometry': 'Coordinates, graphs of linear equations, and the slope and intercept of a line.',
    'icse-graphical-solution': 'Solving simultaneous linear equations by drawing their graphs.',
    'icse-distance-formula': 'The distance between two points and its use in identifying figures.',
  },
  'class-10': {
    'real-numbers': 'The Fundamental Theorem of Arithmetic, HCF and LCM by prime factorisation, and proofs of irrationality.',
    'polynomials': 'Zeroes of a polynomial, what they mean on a graph, and the relation between zeroes and coefficients.',
    'pair-of-linear-equations': 'Solving a pair of linear equations graphically and algebraically, and the conditions for consistency.',
    'quadratic-equations': 'Recognising a quadratic equation, solving it by factorisation and by the formula, and using the discriminant to find the nature of its roots.',
    'icse-quadratic-equations': 'Solving quadratic equations by factorisation and by the formula, and the nature of their roots.',
    'arithmetic-progression':'Arithmetic progressions: the common difference, the nth term and the sum of the first n terms.',
    'triangles': 'Similar triangles: the basic proportionality theorem and the criteria for similarity.',
    'coordinate-geometry': 'The distance formula and the section formula.',
    'trigonometry': 'Trigonometric ratios of an acute angle, their values for standard angles and the three basic identities.',
    'applications-of-trigonometry': 'Heights and distances: using angles of elevation and depression to find lengths.',
    'circles': 'Tangents to a circle and the two tangent theorems.',
    'areas-related-to-circles': 'Areas and perimeters of sectors and segments of a circle.',
    'surface-areas-and-volumes': 'Surface area and volume of solids made by joining cylinders, cones, spheres, hemispheres and cuboids.',
    'statistics': 'Mean, median and mode of grouped data.',
    'probability': 'Theoretical probability of an event, with coins, dice and cards.',
    'icse-gst': 'Goods and Services Tax: CGST, SGST and IGST, and input tax credit.',
    'icse-banking-recurring-deposit-accounts': 'Interest and maturity value of a recurring deposit account.',
    'icse-shares-and-dividend': 'Nominal value and market value of shares, dividend and return on investment.',
    'icse-linear-inequations': 'Solving linear inequations in one variable and representing the solution on a number line.',
    'icse-solving-problems-based-on-quadratic-equations': 'Forming quadratic equations from word problems and choosing the root that fits.',
    'icse-ratio-and-proportion': 'Ratios, proportion, continued proportion and the properties of proportion.',
    'icse-remainder-and-factor-theorems': 'Finding remainders without division and using the factor theorem to factorise polynomials.',
    'icse-matrices': 'Matrices: order, types, addition, multiplication by a number and matrix multiplication.',
    'icse-arithmetic-progression': 'Arithmetic progressions: the common difference, the nth term and the sum of n terms.',
    'icse-geometric-progression': 'Geometric progressions: the common ratio, the nth term and the sum of n terms.',
    'icse-reflection': 'Reflection of points in the axes, the origin and lines parallel to the axes.',
    'icse-section-and-mid-point-formula': 'The section formula, the mid-point formula and the centroid of a triangle.',
    'icse-equation-of-a-line': 'Slope of a line, conditions for parallel and perpendicular lines, and the equation of a line in its different forms.',
    'icse-similarity': 'Similar triangles, the basic proportionality theorem, areas of similar triangles, and maps and models.',
    'icse-loci': 'Loci: the path of a point moving under given conditions, and the standard constructions for them.',
    'icse-circles': 'Angle properties of a circle and cyclic quadrilaterals.',
    'icse-tangents-and-intersecting-chords': 'Tangent properties, intersecting chords, the tangent-secant theorem and the alternate segment theorem.',
    'icse-constructions-circles': 'Constructing tangents to a circle, and the circumscribed and inscribed circles of a triangle and a regular hexagon.',
    'icse-cylinder-cone-and-sphere': 'Surface area and volume of cylinders, cones and spheres, their combinations, and melting and recasting.',
    'icse-trigonometrical-identities': 'The basic trigonometrical identities, ratios of complementary angles and how to prove identities.',
    'icse-heights-and-distances': 'Using angles of elevation and depression to find heights and distances.',
    'icse-graphical-representation-histograms-and-ogives': 'Drawing histograms and ogives, and reading the mode, median and quartiles from them.',
    'icse-measures-of-central-tendency': 'Mean, median, quartiles and mode for raw and grouped data.',
    'icse-probability': 'Probability of an event, with coins, dice and cards.',
  },
};
